// Code generated by protoc-gen-go. DO NOT EDIT.
// source: semantic.proto

package pbsemantic

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveCategoryRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCategoryRequest) Reset()         { *m = RetrieveCategoryRequest{} }
func (m *RetrieveCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoryRequest) ProtoMessage()    {}
func (*RetrieveCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{0}
}

func (m *RetrieveCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoryRequest.Unmarshal(m, b)
}
func (m *RetrieveCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoryRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoryRequest.Merge(m, src)
}
func (m *RetrieveCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoryRequest.Size(m)
}
func (m *RetrieveCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoryRequest proto.InternalMessageInfo

func (m *RetrieveCategoryRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type Category struct {
	Name                   string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId               uint64               `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Childs                 map[uint64]*Category `protobuf:"bytes,3,rep,name=childs,proto3" json:"childs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IdentificationTemplate string               `protobuf:"bytes,4,opt,name=identification_template,json=identificationTemplate,proto3" json:"identification_template,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Category) GetChilds() map[uint64]*Category {
	if m != nil {
		return m.Childs
	}
	return nil
}

func (m *Category) GetIdentificationTemplate() string {
	if m != nil {
		return m.IdentificationTemplate
	}
	return ""
}

type AttributeSchema struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ValueType            string   `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeSchema) Reset()         { *m = AttributeSchema{} }
func (m *AttributeSchema) String() string { return proto.CompactTextString(m) }
func (*AttributeSchema) ProtoMessage()    {}
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{2}
}

func (m *AttributeSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeSchema.Unmarshal(m, b)
}
func (m *AttributeSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeSchema.Marshal(b, m, deterministic)
}
func (m *AttributeSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeSchema.Merge(m, src)
}
func (m *AttributeSchema) XXX_Size() int {
	return xxx_messageInfo_AttributeSchema.Size(m)
}
func (m *AttributeSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeSchema.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeSchema proto.InternalMessageInfo

func (m *AttributeSchema) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *AttributeSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeSchema) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type RetrieveCategoriesResponse struct {
	Categories           map[uint64]*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RetrieveCategoriesResponse) Reset()         { *m = RetrieveCategoriesResponse{} }
func (m *RetrieveCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoriesResponse) ProtoMessage()    {}
func (*RetrieveCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{3}
}

func (m *RetrieveCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoriesResponse.Unmarshal(m, b)
}
func (m *RetrieveCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoriesResponse.Merge(m, src)
}
func (m *RetrieveCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoriesResponse.Size(m)
}
func (m *RetrieveCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoriesResponse proto.InternalMessageInfo

func (m *RetrieveCategoriesResponse) GetCategories() map[uint64]*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type RetrieveAttributesSchemaRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveAttributesSchemaRequest) Reset()         { *m = RetrieveAttributesSchemaRequest{} }
func (m *RetrieveAttributesSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributesSchemaRequest) ProtoMessage()    {}
func (*RetrieveAttributesSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{4}
}

func (m *RetrieveAttributesSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributesSchemaRequest.Unmarshal(m, b)
}
func (m *RetrieveAttributesSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributesSchemaRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributesSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributesSchemaRequest.Merge(m, src)
}
func (m *RetrieveAttributesSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributesSchemaRequest.Size(m)
}
func (m *RetrieveAttributesSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributesSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributesSchemaRequest proto.InternalMessageInfo

func (m *RetrieveAttributesSchemaRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type RetrieveAttributesDataRequest struct {
	EntityId             uint64   `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,2,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveAttributesDataRequest) Reset()         { *m = RetrieveAttributesDataRequest{} }
func (m *RetrieveAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributesDataRequest) ProtoMessage()    {}
func (*RetrieveAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{5}
}

func (m *RetrieveAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributesDataRequest.Unmarshal(m, b)
}
func (m *RetrieveAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributesDataRequest.Merge(m, src)
}
func (m *RetrieveAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributesDataRequest.Size(m)
}
func (m *RetrieveAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributesDataRequest proto.InternalMessageInfo

func (m *RetrieveAttributesDataRequest) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *RetrieveAttributesDataRequest) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type DeleteAttributesDataRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	EntityId             uint64   `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,3,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAttributesDataRequest) Reset()         { *m = DeleteAttributesDataRequest{} }
func (m *DeleteAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAttributesDataRequest) ProtoMessage()    {}
func (*DeleteAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{6}
}

func (m *DeleteAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAttributesDataRequest.Unmarshal(m, b)
}
func (m *DeleteAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAttributesDataRequest.Merge(m, src)
}
func (m *DeleteAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAttributesDataRequest.Size(m)
}
func (m *DeleteAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAttributesDataRequest proto.InternalMessageInfo

func (m *DeleteAttributesDataRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *DeleteAttributesDataRequest) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *DeleteAttributesDataRequest) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type RetrieveAttributesSchemaResponse struct {
	Attributes           []*AttributeSchema `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RetrieveAttributesSchemaResponse) Reset()         { *m = RetrieveAttributesSchemaResponse{} }
func (m *RetrieveAttributesSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributesSchemaResponse) ProtoMessage()    {}
func (*RetrieveAttributesSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{7}
}

func (m *RetrieveAttributesSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributesSchemaResponse.Unmarshal(m, b)
}
func (m *RetrieveAttributesSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributesSchemaResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributesSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributesSchemaResponse.Merge(m, src)
}
func (m *RetrieveAttributesSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributesSchemaResponse.Size(m)
}
func (m *RetrieveAttributesSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributesSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributesSchemaResponse proto.InternalMessageInfo

func (m *RetrieveAttributesSchemaResponse) GetAttributes() []*AttributeSchema {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type RetrieveAttributesDataResponse struct {
	Attributes           []*SetAttributesDataResponse `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RetrieveAttributesDataResponse) Reset()         { *m = RetrieveAttributesDataResponse{} }
func (m *RetrieveAttributesDataResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributesDataResponse) ProtoMessage()    {}
func (*RetrieveAttributesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{8}
}

func (m *RetrieveAttributesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributesDataResponse.Unmarshal(m, b)
}
func (m *RetrieveAttributesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributesDataResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributesDataResponse.Merge(m, src)
}
func (m *RetrieveAttributesDataResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributesDataResponse.Size(m)
}
func (m *RetrieveAttributesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributesDataResponse proto.InternalMessageInfo

func (m *RetrieveAttributesDataResponse) GetAttributes() []*SetAttributesDataResponse {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributesDataResponse struct {
	AttributeDataId      uint64         `protobuf:"varint,1,opt,name=attribute_data_id,json=attributeDataId,proto3" json:"attribute_data_id,omitempty"`
	Data                 *AttributeData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetAttributesDataResponse) Reset()         { *m = SetAttributesDataResponse{} }
func (m *SetAttributesDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataResponse) ProtoMessage()    {}
func (*SetAttributesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{9}
}

func (m *SetAttributesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataResponse.Unmarshal(m, b)
}
func (m *SetAttributesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataResponse.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataResponse.Merge(m, src)
}
func (m *SetAttributesDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataResponse.Size(m)
}
func (m *SetAttributesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataResponse proto.InternalMessageInfo

func (m *SetAttributesDataResponse) GetAttributeDataId() uint64 {
	if m != nil {
		return m.AttributeDataId
	}
	return 0
}

func (m *SetAttributesDataResponse) GetData() *AttributeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CloneAttributesDataResponse struct {
	Attributes           []*SetAttributesDataResponse `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CloneAttributesDataResponse) Reset()         { *m = CloneAttributesDataResponse{} }
func (m *CloneAttributesDataResponse) String() string { return proto.CompactTextString(m) }
func (*CloneAttributesDataResponse) ProtoMessage()    {}
func (*CloneAttributesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{10}
}

func (m *CloneAttributesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributesDataResponse.Unmarshal(m, b)
}
func (m *CloneAttributesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributesDataResponse.Marshal(b, m, deterministic)
}
func (m *CloneAttributesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributesDataResponse.Merge(m, src)
}
func (m *CloneAttributesDataResponse) XXX_Size() int {
	return xxx_messageInfo_CloneAttributesDataResponse.Size(m)
}
func (m *CloneAttributesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributesDataResponse proto.InternalMessageInfo

func (m *CloneAttributesDataResponse) GetAttributes() []*SetAttributesDataResponse {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributesDataRequest struct {
	// Types that are valid to be assigned to Corpus:
	//	*SetAttributesDataRequest_Authorization_
	//	*SetAttributesDataRequest_Data
	Corpus               isSetAttributesDataRequest_Corpus `protobuf_oneof:"corpus"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SetAttributesDataRequest) Reset()         { *m = SetAttributesDataRequest{} }
func (m *SetAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataRequest) ProtoMessage()    {}
func (*SetAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{11}
}

func (m *SetAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataRequest.Unmarshal(m, b)
}
func (m *SetAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataRequest.Merge(m, src)
}
func (m *SetAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataRequest.Size(m)
}
func (m *SetAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataRequest proto.InternalMessageInfo

type isSetAttributesDataRequest_Corpus interface {
	isSetAttributesDataRequest_Corpus()
}

type SetAttributesDataRequest_Authorization_ struct {
	Authorization *SetAttributesDataRequest_Authorization `protobuf:"bytes,1,opt,name=authorization,proto3,oneof"`
}

type SetAttributesDataRequest_Data struct {
	Data *AttributeData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SetAttributesDataRequest_Authorization_) isSetAttributesDataRequest_Corpus() {}

func (*SetAttributesDataRequest_Data) isSetAttributesDataRequest_Corpus() {}

func (m *SetAttributesDataRequest) GetCorpus() isSetAttributesDataRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return nil
}

func (m *SetAttributesDataRequest) GetAuthorization() *SetAttributesDataRequest_Authorization {
	if x, ok := m.GetCorpus().(*SetAttributesDataRequest_Authorization_); ok {
		return x.Authorization
	}
	return nil
}

func (m *SetAttributesDataRequest) GetData() *AttributeData {
	if x, ok := m.GetCorpus().(*SetAttributesDataRequest_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SetAttributesDataRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SetAttributesDataRequest_Authorization_)(nil),
		(*SetAttributesDataRequest_Data)(nil),
	}
}

type SetAttributesDataRequest_Authorization struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	EntityId             uint64   `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,3,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAttributesDataRequest_Authorization) Reset() {
	*m = SetAttributesDataRequest_Authorization{}
}
func (m *SetAttributesDataRequest_Authorization) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataRequest_Authorization) ProtoMessage()    {}
func (*SetAttributesDataRequest_Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{11, 0}
}

func (m *SetAttributesDataRequest_Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Unmarshal(m, b)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataRequest_Authorization.Merge(m, src)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Size(m)
}
func (m *SetAttributesDataRequest_Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataRequest_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataRequest_Authorization proto.InternalMessageInfo

func (m *SetAttributesDataRequest_Authorization) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SetAttributesDataRequest_Authorization) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *SetAttributesDataRequest_Authorization) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type ChangeEntityAttributesDataRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	FromEntityId         uint64   `protobuf:"varint,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	FromEntityTable      string   `protobuf:"bytes,3,opt,name=from_entity_table,json=fromEntityTable,proto3" json:"from_entity_table,omitempty"`
	DestEntityId         uint64   `protobuf:"varint,4,opt,name=dest_entity_id,json=destEntityId,proto3" json:"dest_entity_id,omitempty"`
	DestEntityTable      string   `protobuf:"bytes,5,opt,name=dest_entity_table,json=destEntityTable,proto3" json:"dest_entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEntityAttributesDataRequest) Reset()         { *m = ChangeEntityAttributesDataRequest{} }
func (m *ChangeEntityAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEntityAttributesDataRequest) ProtoMessage()    {}
func (*ChangeEntityAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{12}
}

func (m *ChangeEntityAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEntityAttributesDataRequest.Unmarshal(m, b)
}
func (m *ChangeEntityAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEntityAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEntityAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEntityAttributesDataRequest.Merge(m, src)
}
func (m *ChangeEntityAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEntityAttributesDataRequest.Size(m)
}
func (m *ChangeEntityAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEntityAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEntityAttributesDataRequest proto.InternalMessageInfo

func (m *ChangeEntityAttributesDataRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ChangeEntityAttributesDataRequest) GetFromEntityId() uint64 {
	if m != nil {
		return m.FromEntityId
	}
	return 0
}

func (m *ChangeEntityAttributesDataRequest) GetFromEntityTable() string {
	if m != nil {
		return m.FromEntityTable
	}
	return ""
}

func (m *ChangeEntityAttributesDataRequest) GetDestEntityId() uint64 {
	if m != nil {
		return m.DestEntityId
	}
	return 0
}

func (m *ChangeEntityAttributesDataRequest) GetDestEntityTable() string {
	if m != nil {
		return m.DestEntityTable
	}
	return ""
}

type CloneAttributesDataRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	FromEntityId         uint64   `protobuf:"varint,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	DestEntityId         uint64   `protobuf:"varint,3,opt,name=dest_entity_id,json=destEntityId,proto3" json:"dest_entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,4,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneAttributesDataRequest) Reset()         { *m = CloneAttributesDataRequest{} }
func (m *CloneAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*CloneAttributesDataRequest) ProtoMessage()    {}
func (*CloneAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{13}
}

func (m *CloneAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributesDataRequest.Unmarshal(m, b)
}
func (m *CloneAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *CloneAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributesDataRequest.Merge(m, src)
}
func (m *CloneAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_CloneAttributesDataRequest.Size(m)
}
func (m *CloneAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributesDataRequest proto.InternalMessageInfo

func (m *CloneAttributesDataRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CloneAttributesDataRequest) GetFromEntityId() uint64 {
	if m != nil {
		return m.FromEntityId
	}
	return 0
}

func (m *CloneAttributesDataRequest) GetDestEntityId() uint64 {
	if m != nil {
		return m.DestEntityId
	}
	return 0
}

func (m *CloneAttributesDataRequest) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type AttributeData struct {
	SchemaId             uint64   `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeData) Reset()         { *m = AttributeData{} }
func (m *AttributeData) String() string { return proto.CompactTextString(m) }
func (*AttributeData) ProtoMessage()    {}
func (*AttributeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{14}
}

func (m *AttributeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeData.Unmarshal(m, b)
}
func (m *AttributeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeData.Marshal(b, m, deterministic)
}
func (m *AttributeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeData.Merge(m, src)
}
func (m *AttributeData) XXX_Size() int {
	return xxx_messageInfo_AttributeData.Size(m)
}
func (m *AttributeData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeData.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeData proto.InternalMessageInfo

func (m *AttributeData) GetSchemaId() uint64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *AttributeData) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type PredictCategoryRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictCategoryRequest) Reset()         { *m = PredictCategoryRequest{} }
func (m *PredictCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryRequest) ProtoMessage()    {}
func (*PredictCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{15}
}

func (m *PredictCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryRequest.Unmarshal(m, b)
}
func (m *PredictCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryRequest.Marshal(b, m, deterministic)
}
func (m *PredictCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryRequest.Merge(m, src)
}
func (m *PredictCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryRequest.Size(m)
}
func (m *PredictCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryRequest proto.InternalMessageInfo

func (m *PredictCategoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PredictCategoryResponse struct {
	CategoryId           uint64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Score                float64   `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PredictCategoryResponse) Reset()         { *m = PredictCategoryResponse{} }
func (m *PredictCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryResponse) ProtoMessage()    {}
func (*PredictCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{16}
}

func (m *PredictCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryResponse.Unmarshal(m, b)
}
func (m *PredictCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryResponse.Marshal(b, m, deterministic)
}
func (m *PredictCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryResponse.Merge(m, src)
}
func (m *PredictCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryResponse.Size(m)
}
func (m *PredictCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryResponse proto.InternalMessageInfo

func (m *PredictCategoryResponse) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *PredictCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *PredictCategoryResponse) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type RetrieveCategoriesByRoleRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCategoriesByRoleRequest) Reset()         { *m = RetrieveCategoriesByRoleRequest{} }
func (m *RetrieveCategoriesByRoleRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoriesByRoleRequest) ProtoMessage()    {}
func (*RetrieveCategoriesByRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{17}
}

func (m *RetrieveCategoriesByRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Unmarshal(m, b)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoriesByRoleRequest.Merge(m, src)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Size(m)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoriesByRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoriesByRoleRequest proto.InternalMessageInfo

func (m *RetrieveCategoriesByRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrieveCategoryRequest)(nil), "semantic.RetrieveCategoryRequest")
	proto.RegisterType((*Category)(nil), "semantic.Category")
	proto.RegisterMapType((map[uint64]*Category)(nil), "semantic.Category.ChildsEntry")
	proto.RegisterType((*AttributeSchema)(nil), "semantic.AttributeSchema")
	proto.RegisterType((*RetrieveCategoriesResponse)(nil), "semantic.RetrieveCategoriesResponse")
	proto.RegisterMapType((map[uint64]*Category)(nil), "semantic.RetrieveCategoriesResponse.CategoriesEntry")
	proto.RegisterType((*RetrieveAttributesSchemaRequest)(nil), "semantic.RetrieveAttributesSchemaRequest")
	proto.RegisterType((*RetrieveAttributesDataRequest)(nil), "semantic.RetrieveAttributesDataRequest")
	proto.RegisterType((*DeleteAttributesDataRequest)(nil), "semantic.DeleteAttributesDataRequest")
	proto.RegisterType((*RetrieveAttributesSchemaResponse)(nil), "semantic.RetrieveAttributesSchemaResponse")
	proto.RegisterType((*RetrieveAttributesDataResponse)(nil), "semantic.RetrieveAttributesDataResponse")
	proto.RegisterType((*SetAttributesDataResponse)(nil), "semantic.SetAttributesDataResponse")
	proto.RegisterType((*CloneAttributesDataResponse)(nil), "semantic.CloneAttributesDataResponse")
	proto.RegisterType((*SetAttributesDataRequest)(nil), "semantic.SetAttributesDataRequest")
	proto.RegisterType((*SetAttributesDataRequest_Authorization)(nil), "semantic.SetAttributesDataRequest.Authorization")
	proto.RegisterType((*ChangeEntityAttributesDataRequest)(nil), "semantic.ChangeEntityAttributesDataRequest")
	proto.RegisterType((*CloneAttributesDataRequest)(nil), "semantic.CloneAttributesDataRequest")
	proto.RegisterType((*AttributeData)(nil), "semantic.AttributeData")
	proto.RegisterType((*PredictCategoryRequest)(nil), "semantic.PredictCategoryRequest")
	proto.RegisterType((*PredictCategoryResponse)(nil), "semantic.PredictCategoryResponse")
	proto.RegisterType((*RetrieveCategoriesByRoleRequest)(nil), "semantic.RetrieveCategoriesByRoleRequest")
}

func init() {
	proto.RegisterFile("semantic.proto", fileDescriptor_32e5db2b9bc8653e)
}

var fileDescriptor_32e5db2b9bc8653e = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0x27, 0xd9, 0x55, 0x72, 0xb2, 0xbf, 0x43, 0xb5, 0x49, 0x1d, 0xb5, 0x4d, 0x4c, 0x81,
	0xb0, 0xab, 0x7a, 0xab, 0x80, 0xf8, 0xe9, 0x0d, 0x6a, 0xb2, 0x2b, 0x35, 0x42, 0x95, 0x16, 0x6f,
	0x24, 0x10, 0x02, 0x45, 0x8e, 0x7d, 0x76, 0x63, 0xd5, 0xb1, 0x8d, 0x67, 0x12, 0x29, 0x5c, 0xf1,
	0x2a, 0xbc, 0x40, 0xef, 0x78, 0x04, 0x5e, 0x86, 0x17, 0x40, 0x82, 0x1b, 0xe4, 0x19, 0xff, 0x25,
	0xb1, 0x93, 0x08, 0x5a, 0xa4, 0xde, 0x79, 0xce, 0x7c, 0xe7, 0x9b, 0x6f, 0xce, 0x39, 0x9e, 0x73,
	0xe0, 0x90, 0xe2, 0x44, 0x77, 0x98, 0x65, 0xa8, 0x9e, 0xef, 0x32, 0x97, 0x94, 0xa3, 0xb5, 0x5c,
	0x9b, 0xe9, 0xb6, 0x65, 0xea, 0x0c, 0x2f, 0xa2, 0x0f, 0x01, 0x91, 0x1b, 0x77, 0xae, 0x7b, 0x67,
	0xe3, 0x05, 0x5f, 0x8d, 0xa6, 0xb7, 0x17, 0x38, 0xf1, 0xd8, 0x5c, 0x6c, 0x2a, 0xcf, 0xa0, 0xa6,
	0x21, 0xf3, 0x2d, 0x9c, 0x61, 0x4f, 0x67, 0x78, 0xe7, 0xfa, 0x73, 0x0d, 0x7f, 0x9a, 0x22, 0x65,
	0xe4, 0x11, 0x54, 0x8d, 0xd0, 0x34, 0xb4, 0xcc, 0xba, 0xd4, 0x94, 0xda, 0x25, 0x0d, 0x22, 0x53,
	0xdf, 0x54, 0xfe, 0x96, 0xa0, 0x1c, 0x39, 0x11, 0x02, 0x25, 0x47, 0x9f, 0x20, 0x87, 0x55, 0x34,
	0xfe, 0x4d, 0x1a, 0x50, 0xf1, 0x74, 0x1f, 0x1d, 0x16, 0xf8, 0x17, 0xb8, 0x7f, 0x59, 0x18, 0xfa,
	0x26, 0xf9, 0x0c, 0xf6, 0x8c, 0xb1, 0x65, 0x9b, 0xb4, 0x5e, 0x6c, 0x16, 0xdb, 0xd5, 0xce, 0x43,
	0x35, 0xbe, 0x5a, 0x44, 0xaa, 0xf6, 0x38, 0xe0, 0xca, 0x61, 0xfe, 0x5c, 0x0b, 0xd1, 0xe4, 0x73,
	0xa8, 0x59, 0x26, 0x3a, 0xcc, 0xba, 0xb5, 0x0c, 0x9d, 0x59, 0xae, 0x33, 0x64, 0x38, 0xf1, 0x6c,
	0x9d, 0x61, 0xbd, 0xc4, 0xcf, 0x3e, 0x5d, 0xdc, 0x1e, 0x84, 0xbb, 0xf2, 0x4b, 0xa8, 0xa6, 0xf8,
	0xc8, 0x31, 0x14, 0x5f, 0xe1, 0x3c, 0xbc, 0x56, 0xf0, 0x49, 0xda, 0xb0, 0x3b, 0xd3, 0xed, 0x29,
	0x72, 0xa9, 0xd5, 0x0e, 0x59, 0x15, 0xa4, 0x09, 0xc0, 0xb3, 0xc2, 0x17, 0x92, 0x82, 0x70, 0xf4,
	0x9c, 0x31, 0xdf, 0x1a, 0x4d, 0x19, 0xde, 0x18, 0x63, 0x9c, 0xe8, 0x1b, 0x23, 0x16, 0x07, 0xa9,
	0x90, 0x0a, 0xd2, 0x03, 0x00, 0x4e, 0x3a, 0x64, 0x73, 0x0f, 0xeb, 0x45, 0xbe, 0x53, 0xe1, 0x96,
	0xc1, 0xdc, 0x43, 0xe5, 0x77, 0x09, 0xe4, 0xa5, 0x0c, 0x59, 0x48, 0x35, 0xa4, 0x9e, 0xeb, 0x50,
	0x24, 0x03, 0x88, 0xf8, 0x2d, 0xa4, 0x75, 0x89, 0x47, 0xf2, 0xd3, 0x44, 0x78, 0xbe, 0xa7, 0x9a,
	0x98, 0x44, 0x7c, 0x53, 0x3c, 0xf2, 0x37, 0x70, 0xb4, 0xb4, 0xfd, 0x9f, 0xc3, 0xd5, 0x85, 0x47,
	0x91, 0x98, 0x38, 0x6c, 0x54, 0xc4, 0x6d, 0xeb, 0x82, 0x1b, 0xc2, 0x83, 0x55, 0x8e, 0x4b, 0x9d,
	0xc5, 0x0c, 0x0d, 0xa8, 0x04, 0xa9, 0x67, 0x29, 0xff, 0xb2, 0x30, 0xf4, 0x4d, 0xd2, 0x82, 0xfd,
	0x70, 0x93, 0xe9, 0x23, 0x3b, 0x4a, 0x42, 0x55, 0xd8, 0x06, 0x81, 0x49, 0xf9, 0x45, 0x82, 0xc6,
	0x25, 0xda, 0xc8, 0x72, 0xf8, 0x5b, 0xb0, 0xaf, 0x1b, 0x06, 0x52, 0x3a, 0x64, 0xee, 0x2b, 0x74,
	0xc2, 0x62, 0xaf, 0x0a, 0xdb, 0x20, 0x30, 0x2d, 0x4a, 0x28, 0x6c, 0x90, 0x50, 0x5c, 0x95, 0xf0,
	0x23, 0x34, 0xf3, 0xe3, 0x14, 0x26, 0xfd, 0x4b, 0x00, 0x3d, 0xde, 0x0b, 0x93, 0x7e, 0x3f, 0x09,
	0xff, 0x52, 0x59, 0x6a, 0x29, 0xb0, 0x82, 0xf0, 0x30, 0x2f, 0x84, 0x21, 0x79, 0x2f, 0x83, 0xfc,
	0xfd, 0x84, 0xfc, 0x06, 0x59, 0xb6, 0xe3, 0xc2, 0x31, 0x0c, 0xee, 0xe7, 0x02, 0xc9, 0x19, 0x9c,
	0xc4, 0xd0, 0xa1, 0xa9, 0x33, 0x3d, 0xc9, 0xd6, 0x51, 0xbc, 0x11, 0x78, 0xf4, 0x4d, 0x72, 0x0e,
	0xa5, 0x00, 0x11, 0xd6, 0x58, 0x2d, 0xe3, 0x92, 0x9c, 0x9a, 0x83, 0x94, 0x11, 0x34, 0x7a, 0xb6,
	0xeb, 0xbc, 0xd5, 0x9b, 0xfd, 0x5a, 0x80, 0x7a, 0x06, 0x52, 0xd4, 0xc7, 0x77, 0x70, 0xa0, 0x4f,
	0xd9, 0xd8, 0xf5, 0xad, 0x9f, 0xf9, 0xdb, 0xc3, 0x6f, 0x55, 0xed, 0x3c, 0x5d, 0x7b, 0x08, 0x77,
	0x55, 0x9f, 0xa7, 0xfd, 0x5e, 0xec, 0x68, 0x8b, 0x44, 0xe4, 0xc9, 0x56, 0x71, 0x78, 0xb1, 0x23,
	0x22, 0x21, 0xfb, 0x70, 0xb0, 0x40, 0xf8, 0x3f, 0x54, 0x6e, 0xb7, 0x0c, 0x7b, 0x86, 0xeb, 0x7b,
	0x53, 0xaa, 0xfc, 0x21, 0x41, 0xab, 0x37, 0xd6, 0x9d, 0x3b, 0xbc, 0xe2, 0xfb, 0xff, 0xfa, 0x67,
	0x7a, 0x0c, 0x87, 0xb7, 0xbe, 0x3b, 0x19, 0x2e, 0xeb, 0xda, 0x0f, 0xac, 0x57, 0x91, 0xb6, 0x33,
	0x38, 0x49, 0xa3, 0xd2, 0x02, 0x8f, 0x12, 0x20, 0x17, 0x19, 0x30, 0x9a, 0x48, 0x59, 0x8a, 0xb1,
	0x24, 0x18, 0x03, 0x6b, 0x9a, 0x31, 0x8d, 0x12, 0x8c, 0xbb, 0x82, 0x31, 0x01, 0x8a, 0x1f, 0xf6,
	0xb5, 0x04, 0x72, 0x66, 0xd5, 0xbd, 0xe1, 0x5b, 0xae, 0x2a, 0x2f, 0x66, 0x28, 0x5f, 0xce, 0x53,
	0x69, 0xf5, 0x85, 0xb9, 0x84, 0x83, 0x85, 0xa2, 0x09, 0x12, 0x4f, 0xf9, 0x4b, 0x91, 0x7a, 0x35,
	0x85, 0xa1, 0x6f, 0x92, 0x53, 0xd8, 0xe3, 0x8f, 0x38, 0xad, 0x17, 0x9a, 0xc5, 0x76, 0x45, 0x0b,
	0x57, 0x8a, 0x0a, 0xa7, 0xd7, 0x3e, 0x9a, 0x96, 0xc1, 0x96, 0xe7, 0x86, 0x7b, 0xb0, 0xcb, 0x2c,
	0x66, 0x47, 0xa3, 0x80, 0x58, 0x04, 0x4f, 0x6b, 0x6d, 0xc5, 0x21, 0xfc, 0x31, 0x37, 0xf6, 0x4d,
	0x15, 0xca, 0xd1, 0x6a, 0x4d, 0xb7, 0x89, 0x31, 0x81, 0x04, 0x6a, 0xb8, 0xbe, 0xa8, 0x02, 0x49,
	0x13, 0x0b, 0x65, 0x94, 0xb4, 0xa0, 0xa4, 0xbb, 0x75, 0xe7, 0x9a, 0x6b, 0x63, 0xa4, 0xfd, 0x2b,
	0x28, 0xf9, 0x6e, 0x24, 0xbd, 0x7b, 0xfe, 0x57, 0xb7, 0xed, 0x7f, 0xa8, 0x1d, 0x53, 0xf4, 0x67,
	0x96, 0x81, 0x4f, 0x3c, 0xdf, 0x9d, 0x59, 0x26, 0xfa, 0x5a, 0xd9, 0x70, 0x1d, 0x3a, 0x9d, 0x04,
	0x5f, 0x13, 0xf4, 0x8d, 0xb1, 0xee, 0x30, 0x8d, 0x3b, 0x76, 0x7e, 0x93, 0xe0, 0xf8, 0x46, 0xc0,
	0xaf, 0x43, 0x34, 0x25, 0x03, 0x20, 0xab, 0x07, 0x93, 0x53, 0x55, 0x0c, 0x66, 0x6a, 0x34, 0x98,
	0xa9, 0x57, 0xc1, 0x60, 0x26, 0x3f, 0xde, 0xa6, 0x7d, 0x2b, 0x3b, 0xe4, 0x6b, 0x38, 0x5e, 0x1e,
	0xdd, 0x48, 0x2b, 0xd7, 0x37, 0x4a, 0x8f, 0x9c, 0x11, 0x39, 0x65, 0xa7, 0xf3, 0x5a, 0x82, 0xca,
	0xcb, 0xf0, 0x2a, 0xef, 0x84, 0xe0, 0x3f, 0xf7, 0xa0, 0x7c, 0xed, 0xbb, 0xe6, 0xd4, 0x60, 0x94,
	0xfc, 0x00, 0x47, 0x4b, 0xb5, 0x45, 0x9a, 0x89, 0x57, 0x76, 0x9d, 0xca, 0xad, 0x35, 0x88, 0x48,
	0x73, 0x5b, 0x7a, 0x2a, 0xbd, 0x51, 0xdd, 0x6f, 0x29, 0xb4, 0x14, 0xea, 0x79, 0x53, 0x03, 0xf9,
	0x78, 0x95, 0x23, 0x67, 0x02, 0x93, 0xcf, 0xb6, 0x81, 0xc6, 0x87, 0x4e, 0xe0, 0x34, 0x7b, 0x96,
	0x20, 0x1f, 0xad, 0xe3, 0x49, 0xbd, 0x8e, 0x72, 0x7b, 0x33, 0x30, 0x3e, 0x6e, 0x04, 0x27, 0x2b,
	0xdd, 0x93, 0x28, 0x9b, 0x5b, 0xab, 0xbc, 0x4d, 0x8f, 0x0f, 0x53, 0x6d, 0x80, 0x9c, 0xdf, 0xb8,
	0xc8, 0x79, 0x2a, 0xa3, 0x9b, 0xda, 0x9b, 0x9c, 0x93, 0x52, 0x65, 0x87, 0x98, 0xf0, 0x5e, 0x46,
	0xc3, 0x20, 0xa9, 0x5c, 0xe7, 0xf7, 0x13, 0xf9, 0x83, 0x0d, 0xa8, 0x38, 0x5c, 0xdf, 0xc2, 0xbd,
	0xac, 0x51, 0x96, 0xa4, 0x08, 0xd6, 0x8c, 0xba, 0xf9, 0xf2, 0xbb, 0x87, 0xdf, 0xef, 0xab, 0x17,
	0xde, 0x28, 0x62, 0x19, 0xed, 0x71, 0xc4, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x14, 0x84,
	0xc1, 0x4f, 0x9b, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceProvidersClient is the client API for ServiceProviders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceProvidersClient interface {
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
}

type serviceProvidersClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceProvidersClient(cc grpc.ClientConnInterface) ServiceProvidersClient {
	return &serviceProvidersClient{cc}
}

func (c *serviceProvidersClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceProvidersServer is the server API for ServiceProviders service.
type ServiceProvidersServer interface {
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
}

// UnimplementedServiceProvidersServer can be embedded to have forward compatible implementations.
type UnimplementedServiceProvidersServer struct {
}

func (*UnimplementedServiceProvidersServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedServiceProvidersServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}

func RegisterServiceProvidersServer(s *grpc.Server, srv ServiceProvidersServer) {
	s.RegisterService(&_ServiceProviders_serviceDesc, srv)
}

func _ServiceProviders_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceProviders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.ServiceProviders",
	HandlerType: (*ServiceProvidersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategories",
			Handler:    _ServiceProviders_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveCategory",
			Handler:    _ServiceProviders_RetrieveCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}

// MerchantsClient is the client API for Merchants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsClient interface {
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
}

type merchantsClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantsClient(cc grpc.ClientConnInterface) MerchantsClient {
	return &merchantsClient{cc}
}

func (c *merchantsClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Merchants/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.Merchants/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServer is the server API for Merchants service.
type MerchantsServer interface {
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
}

// UnimplementedMerchantsServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServer struct {
}

func (*UnimplementedMerchantsServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedMerchantsServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}

func RegisterMerchantsServer(s *grpc.Server, srv MerchantsServer) {
	s.RegisterService(&_Merchants_serviceDesc, srv)
}

func _Merchants_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Merchants/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchants_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Merchants/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merchants_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Merchants",
	HandlerType: (*MerchantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategories",
			Handler:    _Merchants_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveCategory",
			Handler:    _Merchants_RetrieveCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveAttributesSchema(ctx context.Context, in *RetrieveAttributesSchemaRequest, opts ...grpc.CallOption) (*RetrieveAttributesSchemaResponse, error)
	RetrieveAttributesData(ctx context.Context, in *RetrieveAttributesDataRequest, opts ...grpc.CallOption) (*RetrieveAttributesDataResponse, error)
	SetAttributesData(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributesDataClient, error)
	ChangeEntityAttributesData(ctx context.Context, in *ChangeEntityAttributesDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CloneAttributesData(ctx context.Context, in *CloneAttributesDataRequest, opts ...grpc.CallOption) (*CloneAttributesDataResponse, error)
	DeleteAttributesData(ctx context.Context, in *DeleteAttributesDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[0], "/semantic.Products/PredictCategory", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsPredictCategoryClient{stream}
	return x, nil
}

type Products_PredictCategoryClient interface {
	Send(*PredictCategoryRequest) error
	Recv() (*PredictCategoryResponse, error)
	grpc.ClientStream
}

type productsPredictCategoryClient struct {
	grpc.ClientStream
}

func (x *productsPredictCategoryClient) Send(m *PredictCategoryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsPredictCategoryClient) Recv() (*PredictCategoryResponse, error) {
	m := new(PredictCategoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveAttributesSchema(ctx context.Context, in *RetrieveAttributesSchemaRequest, opts ...grpc.CallOption) (*RetrieveAttributesSchemaResponse, error) {
	out := new(RetrieveAttributesSchemaResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveAttributesSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveAttributesData(ctx context.Context, in *RetrieveAttributesDataRequest, opts ...grpc.CallOption) (*RetrieveAttributesDataResponse, error) {
	out := new(RetrieveAttributesDataResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveAttributesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) SetAttributesData(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributesDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[1], "/semantic.Products/SetAttributesData", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsSetAttributesDataClient{stream}
	return x, nil
}

type Products_SetAttributesDataClient interface {
	Send(*SetAttributesDataRequest) error
	Recv() (*SetAttributesDataResponse, error)
	grpc.ClientStream
}

type productsSetAttributesDataClient struct {
	grpc.ClientStream
}

func (x *productsSetAttributesDataClient) Send(m *SetAttributesDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsSetAttributesDataClient) Recv() (*SetAttributesDataResponse, error) {
	m := new(SetAttributesDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) ChangeEntityAttributesData(ctx context.Context, in *ChangeEntityAttributesDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/semantic.Products/ChangeEntityAttributesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CloneAttributesData(ctx context.Context, in *CloneAttributesDataRequest, opts ...grpc.CallOption) (*CloneAttributesDataResponse, error) {
	out := new(CloneAttributesDataResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/CloneAttributesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteAttributesData(ctx context.Context, in *DeleteAttributesDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/semantic.Products/DeleteAttributesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	PredictCategory(Products_PredictCategoryServer) error
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveAttributesSchema(context.Context, *RetrieveAttributesSchemaRequest) (*RetrieveAttributesSchemaResponse, error)
	RetrieveAttributesData(context.Context, *RetrieveAttributesDataRequest) (*RetrieveAttributesDataResponse, error)
	SetAttributesData(Products_SetAttributesDataServer) error
	ChangeEntityAttributesData(context.Context, *ChangeEntityAttributesDataRequest) (*empty.Empty, error)
	CloneAttributesData(context.Context, *CloneAttributesDataRequest) (*CloneAttributesDataResponse, error)
	DeleteAttributesData(context.Context, *DeleteAttributesDataRequest) (*empty.Empty, error)
}

// UnimplementedProductsServer can be embedded to have forward compatible implementations.
type UnimplementedProductsServer struct {
}

func (*UnimplementedProductsServer) PredictCategory(srv Products_PredictCategoryServer) error {
	return status.Errorf(codes.Unimplemented, "method PredictCategory not implemented")
}
func (*UnimplementedProductsServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}
func (*UnimplementedProductsServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedProductsServer) RetrieveAttributesSchema(ctx context.Context, req *RetrieveAttributesSchemaRequest) (*RetrieveAttributesSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributesSchema not implemented")
}
func (*UnimplementedProductsServer) RetrieveAttributesData(ctx context.Context, req *RetrieveAttributesDataRequest) (*RetrieveAttributesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributesData not implemented")
}
func (*UnimplementedProductsServer) SetAttributesData(srv Products_SetAttributesDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SetAttributesData not implemented")
}
func (*UnimplementedProductsServer) ChangeEntityAttributesData(ctx context.Context, req *ChangeEntityAttributesDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEntityAttributesData not implemented")
}
func (*UnimplementedProductsServer) CloneAttributesData(ctx context.Context, req *CloneAttributesDataRequest) (*CloneAttributesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneAttributesData not implemented")
}
func (*UnimplementedProductsServer) DeleteAttributesData(ctx context.Context, req *DeleteAttributesDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttributesData not implemented")
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_PredictCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).PredictCategory(&productsPredictCategoryServer{stream})
}

type Products_PredictCategoryServer interface {
	Send(*PredictCategoryResponse) error
	Recv() (*PredictCategoryRequest, error)
	grpc.ServerStream
}

type productsPredictCategoryServer struct {
	grpc.ServerStream
}

func (x *productsPredictCategoryServer) Send(m *PredictCategoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsPredictCategoryServer) Recv() (*PredictCategoryRequest, error) {
	m := new(PredictCategoryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveAttributesSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributesSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveAttributesSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveAttributesSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveAttributesSchema(ctx, req.(*RetrieveAttributesSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveAttributesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveAttributesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveAttributesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveAttributesData(ctx, req.(*RetrieveAttributesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_SetAttributesData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).SetAttributesData(&productsSetAttributesDataServer{stream})
}

type Products_SetAttributesDataServer interface {
	Send(*SetAttributesDataResponse) error
	Recv() (*SetAttributesDataRequest, error)
	grpc.ServerStream
}

type productsSetAttributesDataServer struct {
	grpc.ServerStream
}

func (x *productsSetAttributesDataServer) Send(m *SetAttributesDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsSetAttributesDataServer) Recv() (*SetAttributesDataRequest, error) {
	m := new(SetAttributesDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_ChangeEntityAttributesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEntityAttributesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ChangeEntityAttributesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/ChangeEntityAttributesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ChangeEntityAttributesData(ctx, req.(*ChangeEntityAttributesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CloneAttributesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneAttributesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CloneAttributesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/CloneAttributesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CloneAttributesData(ctx, req.(*CloneAttributesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteAttributesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttributesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteAttributesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/DeleteAttributesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteAttributesData(ctx, req.(*DeleteAttributesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategory",
			Handler:    _Products_RetrieveCategory_Handler,
		},
		{
			MethodName: "RetrieveCategories",
			Handler:    _Products_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveAttributesSchema",
			Handler:    _Products_RetrieveAttributesSchema_Handler,
		},
		{
			MethodName: "RetrieveAttributesData",
			Handler:    _Products_RetrieveAttributesData_Handler,
		},
		{
			MethodName: "ChangeEntityAttributesData",
			Handler:    _Products_ChangeEntityAttributesData_Handler,
		},
		{
			MethodName: "CloneAttributesData",
			Handler:    _Products_CloneAttributesData_Handler,
		},
		{
			MethodName: "DeleteAttributesData",
			Handler:    _Products_DeleteAttributesData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredictCategory",
			Handler:       _Products_PredictCategory_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SetAttributesData",
			Handler:       _Products_SetAttributesData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "semantic.proto",
}
