// Code generated by protoc-gen-go. DO NOT EDIT.
// source: semantic.proto

package pbsemantic

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             uint64      `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Childs               []*Category `protobuf:"bytes,4,rep,name=childs,proto3" json:"childs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Category) GetChilds() []*Category {
	if m != nil {
		return m.Childs
	}
	return nil
}

type AttributeSchema struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           uint64   `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ValueType            string   `protobuf:"bytes,4,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeSchema) Reset()         { *m = AttributeSchema{} }
func (m *AttributeSchema) String() string { return proto.CompactTextString(m) }
func (*AttributeSchema) ProtoMessage()    {}
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{1}
}

func (m *AttributeSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeSchema.Unmarshal(m, b)
}
func (m *AttributeSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeSchema.Marshal(b, m, deterministic)
}
func (m *AttributeSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeSchema.Merge(m, src)
}
func (m *AttributeSchema) XXX_Size() int {
	return xxx_messageInfo_AttributeSchema.Size(m)
}
func (m *AttributeSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeSchema.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeSchema proto.InternalMessageInfo

func (m *AttributeSchema) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AttributeSchema) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *AttributeSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeSchema) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type GetCategoriesResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCategoriesResponse) Reset()         { *m = GetCategoriesResponse{} }
func (m *GetCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesResponse) ProtoMessage()    {}
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{2}
}

func (m *GetCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesResponse.Unmarshal(m, b)
}
func (m *GetCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesResponse.Merge(m, src)
}
func (m *GetCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesResponse.Size(m)
}
func (m *GetCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesResponse proto.InternalMessageInfo

func (m *GetCategoriesResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type GetAttributesSchemaRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttributesSchemaRequest) Reset()         { *m = GetAttributesSchemaRequest{} }
func (m *GetAttributesSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*GetAttributesSchemaRequest) ProtoMessage()    {}
func (*GetAttributesSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{3}
}

func (m *GetAttributesSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesSchemaRequest.Unmarshal(m, b)
}
func (m *GetAttributesSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesSchemaRequest.Marshal(b, m, deterministic)
}
func (m *GetAttributesSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesSchemaRequest.Merge(m, src)
}
func (m *GetAttributesSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_GetAttributesSchemaRequest.Size(m)
}
func (m *GetAttributesSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesSchemaRequest proto.InternalMessageInfo

func (m *GetAttributesSchemaRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type GetAttributesSchemaResponse struct {
	Attributes           []*AttributeSchema `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAttributesSchemaResponse) Reset()         { *m = GetAttributesSchemaResponse{} }
func (m *GetAttributesSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttributesSchemaResponse) ProtoMessage()    {}
func (*GetAttributesSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{4}
}

func (m *GetAttributesSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesSchemaResponse.Unmarshal(m, b)
}
func (m *GetAttributesSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesSchemaResponse.Marshal(b, m, deterministic)
}
func (m *GetAttributesSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesSchemaResponse.Merge(m, src)
}
func (m *GetAttributesSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttributesSchemaResponse.Size(m)
}
func (m *GetAttributesSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesSchemaResponse proto.InternalMessageInfo

func (m *GetAttributesSchemaResponse) GetAttributes() []*AttributeSchema {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributesDataResponse struct {
	AttributeDataId      uint64         `protobuf:"varint,1,opt,name=attribute_data_id,json=attributeDataId,proto3" json:"attribute_data_id,omitempty"`
	Data                 *AttributeData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetAttributesDataResponse) Reset()         { *m = SetAttributesDataResponse{} }
func (m *SetAttributesDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataResponse) ProtoMessage()    {}
func (*SetAttributesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{5}
}

func (m *SetAttributesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataResponse.Unmarshal(m, b)
}
func (m *SetAttributesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataResponse.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataResponse.Merge(m, src)
}
func (m *SetAttributesDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataResponse.Size(m)
}
func (m *SetAttributesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataResponse proto.InternalMessageInfo

func (m *SetAttributesDataResponse) GetAttributeDataId() uint64 {
	if m != nil {
		return m.AttributeDataId
	}
	return 0
}

func (m *SetAttributesDataResponse) GetData() *AttributeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CloneAttributesDataResponse struct {
	Attributes           []*SetAttributesDataResponse `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CloneAttributesDataResponse) Reset()         { *m = CloneAttributesDataResponse{} }
func (m *CloneAttributesDataResponse) String() string { return proto.CompactTextString(m) }
func (*CloneAttributesDataResponse) ProtoMessage()    {}
func (*CloneAttributesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{6}
}

func (m *CloneAttributesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributesDataResponse.Unmarshal(m, b)
}
func (m *CloneAttributesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributesDataResponse.Marshal(b, m, deterministic)
}
func (m *CloneAttributesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributesDataResponse.Merge(m, src)
}
func (m *CloneAttributesDataResponse) XXX_Size() int {
	return xxx_messageInfo_CloneAttributesDataResponse.Size(m)
}
func (m *CloneAttributesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributesDataResponse proto.InternalMessageInfo

func (m *CloneAttributesDataResponse) GetAttributes() []*SetAttributesDataResponse {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributesDataRequest struct {
	// Types that are valid to be assigned to Corpus:
	//	*SetAttributesDataRequest_Authorization_
	//	*SetAttributesDataRequest_Data
	Corpus               isSetAttributesDataRequest_Corpus `protobuf_oneof:"corpus"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SetAttributesDataRequest) Reset()         { *m = SetAttributesDataRequest{} }
func (m *SetAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataRequest) ProtoMessage()    {}
func (*SetAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{7}
}

func (m *SetAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataRequest.Unmarshal(m, b)
}
func (m *SetAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataRequest.Merge(m, src)
}
func (m *SetAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataRequest.Size(m)
}
func (m *SetAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataRequest proto.InternalMessageInfo

type isSetAttributesDataRequest_Corpus interface {
	isSetAttributesDataRequest_Corpus()
}

type SetAttributesDataRequest_Authorization_ struct {
	Authorization *SetAttributesDataRequest_Authorization `protobuf:"bytes,1,opt,name=authorization,proto3,oneof"`
}

type SetAttributesDataRequest_Data struct {
	Data *AttributeData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SetAttributesDataRequest_Authorization_) isSetAttributesDataRequest_Corpus() {}

func (*SetAttributesDataRequest_Data) isSetAttributesDataRequest_Corpus() {}

func (m *SetAttributesDataRequest) GetCorpus() isSetAttributesDataRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return nil
}

func (m *SetAttributesDataRequest) GetAuthorization() *SetAttributesDataRequest_Authorization {
	if x, ok := m.GetCorpus().(*SetAttributesDataRequest_Authorization_); ok {
		return x.Authorization
	}
	return nil
}

func (m *SetAttributesDataRequest) GetData() *AttributeData {
	if x, ok := m.GetCorpus().(*SetAttributesDataRequest_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SetAttributesDataRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SetAttributesDataRequest_Authorization_)(nil),
		(*SetAttributesDataRequest_Data)(nil),
	}
}

type SetAttributesDataRequest_Authorization struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	EntityId             uint64   `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,3,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAttributesDataRequest_Authorization) Reset() {
	*m = SetAttributesDataRequest_Authorization{}
}
func (m *SetAttributesDataRequest_Authorization) String() string { return proto.CompactTextString(m) }
func (*SetAttributesDataRequest_Authorization) ProtoMessage()    {}
func (*SetAttributesDataRequest_Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{7, 0}
}

func (m *SetAttributesDataRequest_Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Unmarshal(m, b)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Marshal(b, m, deterministic)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesDataRequest_Authorization.Merge(m, src)
}
func (m *SetAttributesDataRequest_Authorization) XXX_Size() int {
	return xxx_messageInfo_SetAttributesDataRequest_Authorization.Size(m)
}
func (m *SetAttributesDataRequest_Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesDataRequest_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesDataRequest_Authorization proto.InternalMessageInfo

func (m *SetAttributesDataRequest_Authorization) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SetAttributesDataRequest_Authorization) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *SetAttributesDataRequest_Authorization) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type CloneAttributesDataRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	FromEntityId         uint64   `protobuf:"varint,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	DestEntityId         uint64   `protobuf:"varint,3,opt,name=dest_entity_id,json=destEntityId,proto3" json:"dest_entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,4,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneAttributesDataRequest) Reset()         { *m = CloneAttributesDataRequest{} }
func (m *CloneAttributesDataRequest) String() string { return proto.CompactTextString(m) }
func (*CloneAttributesDataRequest) ProtoMessage()    {}
func (*CloneAttributesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{8}
}

func (m *CloneAttributesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributesDataRequest.Unmarshal(m, b)
}
func (m *CloneAttributesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributesDataRequest.Marshal(b, m, deterministic)
}
func (m *CloneAttributesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributesDataRequest.Merge(m, src)
}
func (m *CloneAttributesDataRequest) XXX_Size() int {
	return xxx_messageInfo_CloneAttributesDataRequest.Size(m)
}
func (m *CloneAttributesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributesDataRequest proto.InternalMessageInfo

func (m *CloneAttributesDataRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CloneAttributesDataRequest) GetFromEntityId() uint64 {
	if m != nil {
		return m.FromEntityId
	}
	return 0
}

func (m *CloneAttributesDataRequest) GetDestEntityId() uint64 {
	if m != nil {
		return m.DestEntityId
	}
	return 0
}

func (m *CloneAttributesDataRequest) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type AttributeData struct {
	SchemaId             uint64   `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeData) Reset()         { *m = AttributeData{} }
func (m *AttributeData) String() string { return proto.CompactTextString(m) }
func (*AttributeData) ProtoMessage()    {}
func (*AttributeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{9}
}

func (m *AttributeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeData.Unmarshal(m, b)
}
func (m *AttributeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeData.Marshal(b, m, deterministic)
}
func (m *AttributeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeData.Merge(m, src)
}
func (m *AttributeData) XXX_Size() int {
	return xxx_messageInfo_AttributeData.Size(m)
}
func (m *AttributeData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeData.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeData proto.InternalMessageInfo

func (m *AttributeData) GetSchemaId() uint64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *AttributeData) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type PredictCategoryRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictCategoryRequest) Reset()         { *m = PredictCategoryRequest{} }
func (m *PredictCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryRequest) ProtoMessage()    {}
func (*PredictCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{10}
}

func (m *PredictCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryRequest.Unmarshal(m, b)
}
func (m *PredictCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryRequest.Marshal(b, m, deterministic)
}
func (m *PredictCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryRequest.Merge(m, src)
}
func (m *PredictCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryRequest.Size(m)
}
func (m *PredictCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryRequest proto.InternalMessageInfo

func (m *PredictCategoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PredictCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Score                float64   `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PredictCategoryResponse) Reset()         { *m = PredictCategoryResponse{} }
func (m *PredictCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryResponse) ProtoMessage()    {}
func (*PredictCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{11}
}

func (m *PredictCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryResponse.Unmarshal(m, b)
}
func (m *PredictCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryResponse.Marshal(b, m, deterministic)
}
func (m *PredictCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryResponse.Merge(m, src)
}
func (m *PredictCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryResponse.Size(m)
}
func (m *PredictCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryResponse proto.InternalMessageInfo

func (m *PredictCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *PredictCategoryResponse) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*Category)(nil), "semantic.Category")
	proto.RegisterType((*AttributeSchema)(nil), "semantic.AttributeSchema")
	proto.RegisterType((*GetCategoriesResponse)(nil), "semantic.GetCategoriesResponse")
	proto.RegisterType((*GetAttributesSchemaRequest)(nil), "semantic.GetAttributesSchemaRequest")
	proto.RegisterType((*GetAttributesSchemaResponse)(nil), "semantic.GetAttributesSchemaResponse")
	proto.RegisterType((*SetAttributesDataResponse)(nil), "semantic.SetAttributesDataResponse")
	proto.RegisterType((*CloneAttributesDataResponse)(nil), "semantic.CloneAttributesDataResponse")
	proto.RegisterType((*SetAttributesDataRequest)(nil), "semantic.SetAttributesDataRequest")
	proto.RegisterType((*SetAttributesDataRequest_Authorization)(nil), "semantic.SetAttributesDataRequest.Authorization")
	proto.RegisterType((*CloneAttributesDataRequest)(nil), "semantic.CloneAttributesDataRequest")
	proto.RegisterType((*AttributeData)(nil), "semantic.AttributeData")
	proto.RegisterType((*PredictCategoryRequest)(nil), "semantic.PredictCategoryRequest")
	proto.RegisterType((*PredictCategoryResponse)(nil), "semantic.PredictCategoryResponse")
}

func init() {
	proto.RegisterFile("semantic.proto", fileDescriptor_32e5db2b9bc8653e)
}

var fileDescriptor_32e5db2b9bc8653e = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x15, 0x25, 0x55, 0xa0, 0x46, 0x17, 0xd7, 0xeb, 0xd6, 0xa6, 0x29, 0x14, 0x96, 0x59, 0x17,
	0x10, 0x5c, 0x94, 0x32, 0xd4, 0xa7, 0x3e, 0xf4, 0xc1, 0x37, 0xd8, 0x6a, 0x11, 0xc0, 0xa0, 0x0d,
	0xc4, 0x08, 0x82, 0x08, 0x2b, 0xee, 0xda, 0x5a, 0x44, 0x22, 0x19, 0xee, 0x52, 0x81, 0xf2, 0x37,
	0xf9, 0x81, 0x7c, 0x55, 0x3e, 0x24, 0x20, 0x97, 0x37, 0x49, 0x94, 0xed, 0x07, 0xbf, 0x71, 0x67,
	0xcf, 0xcc, 0x9c, 0x39, 0xdc, 0x39, 0xd0, 0xe6, 0x74, 0x86, 0x1d, 0xc1, 0x6c, 0xd3, 0xf3, 0x5d,
	0xe1, 0x22, 0x35, 0x39, 0xeb, 0x7b, 0x73, 0x3c, 0x65, 0x04, 0x0b, 0xda, 0x4f, 0x3e, 0x24, 0x44,
	0xef, 0x3c, 0xba, 0xee, 0xe3, 0x94, 0xf6, 0xa3, 0xd3, 0x38, 0x78, 0xe8, 0xd3, 0x99, 0x27, 0x16,
	0xf2, 0xd2, 0xf8, 0x0c, 0xea, 0x39, 0x16, 0xf4, 0xd1, 0xf5, 0x17, 0xa8, 0x0d, 0x65, 0x46, 0x34,
	0xa5, 0xab, 0xf4, 0xaa, 0x56, 0x99, 0x11, 0x84, 0xa0, 0xea, 0xe0, 0x19, 0xd5, 0xca, 0x5d, 0xa5,
	0x57, 0xb7, 0xa2, 0x6f, 0xd4, 0x81, 0xba, 0x87, 0x7d, 0xea, 0x88, 0x11, 0x23, 0x5a, 0x25, 0x82,
	0xaa, 0x32, 0x30, 0x24, 0xe8, 0x18, 0x6a, 0xf6, 0x84, 0x4d, 0x09, 0xd7, 0xaa, 0xdd, 0x4a, 0xaf,
	0x31, 0x40, 0x66, 0xca, 0x36, 0x69, 0x62, 0xc5, 0x08, 0x23, 0x80, 0xad, 0x53, 0x21, 0x7c, 0x36,
	0x0e, 0x04, 0xbd, 0xb5, 0x27, 0x74, 0x86, 0xd7, 0xfa, 0x1f, 0x40, 0xc3, 0x8e, 0xd3, 0xc2, 0x6e,
	0xe5, 0xe8, 0x02, 0x92, 0xd0, 0x30, 0x23, 0x58, 0xc9, 0x11, 0xfc, 0x0d, 0x60, 0x8e, 0xa7, 0x01,
	0x1d, 0x89, 0x85, 0x47, 0xb5, 0x6a, 0x74, 0x53, 0x8f, 0x22, 0x77, 0x0b, 0x8f, 0x1a, 0xff, 0xc3,
	0xaf, 0x57, 0x54, 0xc4, 0x6c, 0x18, 0xe5, 0x16, 0xe5, 0x9e, 0xeb, 0x70, 0x8a, 0x06, 0x90, 0x54,
	0x66, 0x94, 0x6b, 0xca, 0x46, 0xfe, 0x39, 0x94, 0xf1, 0x2f, 0xe8, 0x57, 0x54, 0xa4, 0x63, 0x70,
	0x39, 0x87, 0x45, 0x3f, 0x05, 0x94, 0x8b, 0x55, 0xfa, 0xca, 0x2a, 0x7d, 0xe3, 0x1e, 0x3a, 0x85,
	0xe9, 0x31, 0xa3, 0x7f, 0x00, 0x70, 0x7a, 0x17, 0x33, 0xda, 0xcf, 0x18, 0xad, 0xa8, 0x67, 0xe5,
	0xc0, 0x86, 0x80, 0xfd, 0xdb, 0x7c, 0xe5, 0x0b, 0x2c, 0xb2, 0xba, 0xc7, 0xb0, 0x9d, 0x42, 0x47,
	0x04, 0x0b, 0x9c, 0xb1, 0xdb, 0x4a, 0x2f, 0xc2, 0x8c, 0x21, 0x41, 0x7f, 0x42, 0x35, 0x44, 0x44,
	0xda, 0x37, 0x06, 0x7b, 0x05, 0xdd, 0xa3, 0xd2, 0x11, 0xc8, 0x18, 0x43, 0xe7, 0x7c, 0xea, 0x3a,
	0x74, 0x43, 0xdf, 0xf3, 0x82, 0x79, 0x7e, 0xcf, 0x2a, 0x6e, 0x24, 0xbc, 0x34, 0xd9, 0xd7, 0x32,
	0x68, 0x05, 0x48, 0xa9, 0xf8, 0x3d, 0xb4, 0x70, 0x20, 0x26, 0xae, 0xcf, 0xbe, 0x60, 0xc1, 0x5c,
	0x27, 0x9a, 0xaa, 0x31, 0x38, 0x79, 0xb2, 0x49, 0x94, 0x6a, 0x9e, 0xe6, 0xf3, 0xae, 0x4b, 0xd6,
	0x72, 0x21, 0xf4, 0xd7, 0x8b, 0x74, 0xb8, 0x2e, 0x49, 0x25, 0x74, 0x1f, 0x5a, 0x4b, 0x05, 0xd1,
	0x21, 0x34, 0xb1, 0x6d, 0x53, 0xce, 0x47, 0xc2, 0xfd, 0x48, 0x25, 0xb1, 0xba, 0xd5, 0x90, 0xb1,
	0xbb, 0x30, 0x14, 0x6e, 0x16, 0x75, 0x04, 0x13, 0xb9, 0xb7, 0xae, 0xca, 0xc0, 0x90, 0x84, 0xf9,
	0xf1, 0xa5, 0xc0, 0xe3, 0x69, 0xf2, 0xe2, 0x1b, 0x32, 0x76, 0x17, 0x86, 0xce, 0x54, 0xa8, 0xd9,
	0xae, 0xef, 0x05, 0xdc, 0xf8, 0xa6, 0x80, 0x5e, 0xf8, 0x23, 0xa4, 0x4a, 0x2f, 0xe0, 0x72, 0x04,
	0xed, 0x07, 0xdf, 0x9d, 0x8d, 0x56, 0x09, 0x35, 0xc3, 0xe8, 0x65, 0x42, 0xea, 0x08, 0xda, 0x84,
	0x72, 0x91, 0x43, 0x49, 0x43, 0x68, 0x86, 0xd1, 0xcb, 0x4d, 0xd4, 0xab, 0x6b, 0xd4, 0x8d, 0x0b,
	0x68, 0x2d, 0xe9, 0x18, 0x6a, 0xc1, 0xa3, 0x57, 0x9d, 0x3d, 0x4d, 0x55, 0x06, 0x86, 0x04, 0xed,
	0x42, 0x2d, 0xda, 0x67, 0xae, 0x95, 0xbb, 0x95, 0x5e, 0xdd, 0x8a, 0x4f, 0x86, 0x09, 0xbb, 0x37,
	0x3e, 0x25, 0xcc, 0x16, 0xe9, 0xb2, 0xc6, 0x13, 0xff, 0x02, 0x3f, 0x09, 0x26, 0xa6, 0x34, 0x1e,
	0x55, 0x1e, 0x8c, 0x11, 0xec, 0xad, 0xe1, 0xe3, 0xa7, 0x6a, 0x82, 0x9a, 0xec, 0x69, 0xfc, 0x86,
	0x8a, 0xac, 0x20, 0xc5, 0x84, 0x0d, 0xb8, 0xed, 0xfa, 0xd2, 0x2a, 0x15, 0x4b, 0x1e, 0x06, 0x1f,
	0xe0, 0xe7, 0x5b, 0xea, 0xcf, 0x99, 0x4d, 0x6f, 0x7c, 0x77, 0xce, 0x08, 0xf5, 0x39, 0xfa, 0x0f,
	0x5a, 0x4b, 0xfe, 0x83, 0x76, 0x4d, 0x69, 0xcf, 0x66, 0x62, 0xcf, 0xe6, 0x65, 0x68, 0xcf, 0xfa,
	0x41, 0xd6, 0xb0, 0xd0, 0xb0, 0x8c, 0xd2, 0xe0, 0x2d, 0xd4, 0xdf, 0x50, 0xdf, 0x9e, 0x60, 0x47,
	0xbc, 0x6e, 0xe1, 0xef, 0x15, 0x50, 0x6f, 0x7c, 0x97, 0x04, 0xb6, 0xe0, 0xe8, 0x3d, 0x6c, 0xad,
	0xc8, 0x84, 0xba, 0x59, 0x89, 0x62, 0xc5, 0xf5, 0xc3, 0x27, 0x10, 0x49, 0x9b, 0x9e, 0x72, 0xa2,
	0xbc, 0x26, 0x6d, 0x44, 0x60, 0xa7, 0xc0, 0x4f, 0xd1, 0xd1, 0x52, 0xe6, 0x06, 0xb7, 0xd6, 0xff,
	0x78, 0x06, 0x95, 0x76, 0x19, 0xc3, 0xf6, 0x9a, 0x8b, 0x20, 0xe3, 0x79, 0x8b, 0xd1, 0x5f, 0xe2,
	0x75, 0xb1, 0x2a, 0x04, 0x76, 0x0a, 0x16, 0x38, 0x3f, 0xc9, 0xe6, 0xfd, 0xce, 0x4f, 0xf2, 0x84,
	0x1d, 0x1b, 0xa5, 0xb3, 0xf6, 0xbb, 0xa6, 0xd9, 0xf7, 0xc6, 0x09, 0x7a, 0x5c, 0x8b, 0x24, 0xff,
	0xfb, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x21, 0xdf, 0xf4, 0x64, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceProvidersClient is the client API for ServiceProviders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceProvidersClient interface {
	GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
}

type serviceProvidersClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceProvidersClient(cc grpc.ClientConnInterface) ServiceProvidersClient {
	return &serviceProvidersClient{cc}
}

func (c *serviceProvidersClient) GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceProvidersServer is the server API for ServiceProviders service.
type ServiceProvidersServer interface {
	GetCategories(context.Context, *empty.Empty) (*GetCategoriesResponse, error)
}

// UnimplementedServiceProvidersServer can be embedded to have forward compatible implementations.
type UnimplementedServiceProvidersServer struct {
}

func (*UnimplementedServiceProvidersServer) GetCategories(ctx context.Context, req *empty.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}

func RegisterServiceProvidersServer(s *grpc.Server, srv ServiceProvidersServer) {
	s.RegisterService(&_ServiceProviders_serviceDesc, srv)
}

func _ServiceProviders_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).GetCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceProviders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.ServiceProviders",
	HandlerType: (*ServiceProvidersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _ServiceProviders_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}

// MerchantsClient is the client API for Merchants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsClient interface {
	GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
}

type merchantsClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantsClient(cc grpc.ClientConnInterface) MerchantsClient {
	return &merchantsClient{cc}
}

func (c *merchantsClient) GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Merchants/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServer is the server API for Merchants service.
type MerchantsServer interface {
	GetCategories(context.Context, *empty.Empty) (*GetCategoriesResponse, error)
}

// UnimplementedMerchantsServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServer struct {
}

func (*UnimplementedMerchantsServer) GetCategories(ctx context.Context, req *empty.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}

func RegisterMerchantsServer(s *grpc.Server, srv MerchantsServer) {
	s.RegisterService(&_Merchants_serviceDesc, srv)
}

func _Merchants_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Merchants/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServer).GetCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merchants_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Merchants",
	HandlerType: (*MerchantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _Merchants_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error)
	GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	GetAttributesSchema(ctx context.Context, in *GetAttributesSchemaRequest, opts ...grpc.CallOption) (*GetAttributesSchemaResponse, error)
	SetAttributesData(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributesDataClient, error)
	CloneAttributesData(ctx context.Context, in *CloneAttributesDataRequest, opts ...grpc.CallOption) (*CloneAttributesDataResponse, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[0], "/semantic.Products/PredictCategory", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsPredictCategoryClient{stream}
	return x, nil
}

type Products_PredictCategoryClient interface {
	Send(*PredictCategoryRequest) error
	Recv() (*PredictCategoryResponse, error)
	grpc.ClientStream
}

type productsPredictCategoryClient struct {
	grpc.ClientStream
}

func (x *productsPredictCategoryClient) Send(m *PredictCategoryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsPredictCategoryClient) Recv() (*PredictCategoryResponse, error) {
	m := new(PredictCategoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) GetCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetAttributesSchema(ctx context.Context, in *GetAttributesSchemaRequest, opts ...grpc.CallOption) (*GetAttributesSchemaResponse, error) {
	out := new(GetAttributesSchemaResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/GetAttributesSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) SetAttributesData(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributesDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[1], "/semantic.Products/SetAttributesData", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsSetAttributesDataClient{stream}
	return x, nil
}

type Products_SetAttributesDataClient interface {
	Send(*SetAttributesDataRequest) error
	Recv() (*SetAttributesDataResponse, error)
	grpc.ClientStream
}

type productsSetAttributesDataClient struct {
	grpc.ClientStream
}

func (x *productsSetAttributesDataClient) Send(m *SetAttributesDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsSetAttributesDataClient) Recv() (*SetAttributesDataResponse, error) {
	m := new(SetAttributesDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) CloneAttributesData(ctx context.Context, in *CloneAttributesDataRequest, opts ...grpc.CallOption) (*CloneAttributesDataResponse, error) {
	out := new(CloneAttributesDataResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/CloneAttributesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	PredictCategory(Products_PredictCategoryServer) error
	GetCategories(context.Context, *empty.Empty) (*GetCategoriesResponse, error)
	GetAttributesSchema(context.Context, *GetAttributesSchemaRequest) (*GetAttributesSchemaResponse, error)
	SetAttributesData(Products_SetAttributesDataServer) error
	CloneAttributesData(context.Context, *CloneAttributesDataRequest) (*CloneAttributesDataResponse, error)
}

// UnimplementedProductsServer can be embedded to have forward compatible implementations.
type UnimplementedProductsServer struct {
}

func (*UnimplementedProductsServer) PredictCategory(srv Products_PredictCategoryServer) error {
	return status.Errorf(codes.Unimplemented, "method PredictCategory not implemented")
}
func (*UnimplementedProductsServer) GetCategories(ctx context.Context, req *empty.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (*UnimplementedProductsServer) GetAttributesSchema(ctx context.Context, req *GetAttributesSchemaRequest) (*GetAttributesSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributesSchema not implemented")
}
func (*UnimplementedProductsServer) SetAttributesData(srv Products_SetAttributesDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SetAttributesData not implemented")
}
func (*UnimplementedProductsServer) CloneAttributesData(ctx context.Context, req *CloneAttributesDataRequest) (*CloneAttributesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneAttributesData not implemented")
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_PredictCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).PredictCategory(&productsPredictCategoryServer{stream})
}

type Products_PredictCategoryServer interface {
	Send(*PredictCategoryResponse) error
	Recv() (*PredictCategoryRequest, error)
	grpc.ServerStream
}

type productsPredictCategoryServer struct {
	grpc.ServerStream
}

func (x *productsPredictCategoryServer) Send(m *PredictCategoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsPredictCategoryServer) Recv() (*PredictCategoryRequest, error) {
	m := new(PredictCategoryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetAttributesSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetAttributesSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/GetAttributesSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetAttributesSchema(ctx, req.(*GetAttributesSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_SetAttributesData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).SetAttributesData(&productsSetAttributesDataServer{stream})
}

type Products_SetAttributesDataServer interface {
	Send(*SetAttributesDataResponse) error
	Recv() (*SetAttributesDataRequest, error)
	grpc.ServerStream
}

type productsSetAttributesDataServer struct {
	grpc.ServerStream
}

func (x *productsSetAttributesDataServer) Send(m *SetAttributesDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsSetAttributesDataServer) Recv() (*SetAttributesDataRequest, error) {
	m := new(SetAttributesDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_CloneAttributesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneAttributesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CloneAttributesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/CloneAttributesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CloneAttributesData(ctx, req.(*CloneAttributesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _Products_GetCategories_Handler,
		},
		{
			MethodName: "GetAttributesSchema",
			Handler:    _Products_GetAttributesSchema_Handler,
		},
		{
			MethodName: "CloneAttributesData",
			Handler:    _Products_CloneAttributesData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredictCategory",
			Handler:       _Products_PredictCategory_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SetAttributesData",
			Handler:       _Products_SetAttributesData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "semantic.proto",
}
