#!/bin/sh
DIR=$(dirname "$0")
DIR=${DIR}/backend

GREENa="\e[1;44m"
GREENb="\e[0m"
for svc in address auth identifier images mailer products semantic services users
do
  cd $DIR/$svc || cd ../$svc

  echo "${GREENa}Checking${GREENb} ${svc}"
  make check --silent
done
