#!/bin/sh
DIR=$(dirname "$0")
cd $DIR/pb
#  --js_out="library=pb_$1,binary:js" \

pbcompile()
{
protoc \
  -I . \
  -I ${GOPATH}/src \
  -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate \
  --go_out="plugins=grpc:../backend/$1/pb/" \
  --validate_out="lang=go:../backend/$1/pb/" \
  $1.proto

../cleanpb ./$1.proto > ./clean/$1.proto
}

pbpropague()
{
	cp -r ../backend/$1/pb/pb$1 ../backend/$2/pb/
}

pbcompile users

pbcompile semantic

pbcompile identifier

pbcompile auth

pbcompile mailer

pbcompile products

pbcompile images


pbpropague auth users

pbpropague auth products

pbpropague images products

pbpropague auth images

pbpropague identifier users

pbpropague auth semantic

pbpropague products semantic

pbpropague users products

pbpropague semantic products

pbpropague semantic users

pbpropague mailer users


echo "Done"
