#!/bin/sh
DIR=$(dirname "$0")
cd $DIR/pb
#  --js_out="library=pb_$1,binary:js" \

pbcompile()
{
protoc \
  -I . \
  -I ${GOPATH}/src \
  -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate \
  --go_out="plugins=grpc:../backend/$2/pb/" \
  --validate_out="lang=go:../backend/$2/pb/" \
  $1.proto

../pbclean ./$1.proto > ./$1.clean.proto
}

pbpropague()
{
	cp -r ../backend/$2/pb/pb$1 ../backend/$3/pb/
}

pbcompile user users

pbcompile identifier identifier

pbcompile auth auth

pbcompile mailer mailer

pbpropague auth auth users

pbpropague identifier identifier users

pbpropague mailer mailer users

echo "Done"
