#!/bin/sh
DIR=$(dirname "$0")
cd $DIR/pb

protoc \
  -I . \
  -I ${GOPATH}/src \
  -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate \
  --go_out="../backend/users/" \
  --js_out="library=pb_user,binary:js" \
  --validate_out="lang=go:../backend/users/" \
  user.proto
