export const LoaderTypes = {
  // Example
  FETCH_FAKE_DATA: 'FETCH_FAKE_DATA',
  // Global
  ON_COUNT_CHANGE: 'ON_COUNT_CHANGE',
  // ATUH
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  VERIFY_ACCOUNT: 'VERIFY_ACCOUNT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  // USER
  FETCH_ME: 'FETCH_ME',
  UPDATE_ME: 'UPDATE_ME',
};

export const LoaderStatus = {
  LOADING: 'LOADING',
  END: 'END',
  ERROR: 'ERROR',
};
