// Code generated by protoc-gen-go. DO NOT EDIT.
// source: semantic.proto

package pbsemantic

import (
	context "context"
	fmt "fmt"
	pbshared "github.com/athomecomar/athome/pb/pbshared"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveShippingCategoriesRequest struct {
	MaxVolWeight         float64  `protobuf:"fixed64,1,opt,name=max_vol_weight,json=maxVolWeight,proto3" json:"max_vol_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveShippingCategoriesRequest) Reset()         { *m = RetrieveShippingCategoriesRequest{} }
func (m *RetrieveShippingCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveShippingCategoriesRequest) ProtoMessage()    {}
func (*RetrieveShippingCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{0}
}

func (m *RetrieveShippingCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveShippingCategoriesRequest.Unmarshal(m, b)
}
func (m *RetrieveShippingCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveShippingCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveShippingCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveShippingCategoriesRequest.Merge(m, src)
}
func (m *RetrieveShippingCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveShippingCategoriesRequest.Size(m)
}
func (m *RetrieveShippingCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveShippingCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveShippingCategoriesRequest proto.InternalMessageInfo

func (m *RetrieveShippingCategoriesRequest) GetMaxVolWeight() float64 {
	if m != nil {
		return m.MaxVolWeight
	}
	return 0
}

type RetrieveCategoriesByIdRequest struct {
	CategoryIds          []uint64 `protobuf:"varint,1,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCategoriesByIdRequest) Reset()         { *m = RetrieveCategoriesByIdRequest{} }
func (m *RetrieveCategoriesByIdRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoriesByIdRequest) ProtoMessage()    {}
func (*RetrieveCategoriesByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{1}
}

func (m *RetrieveCategoriesByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoriesByIdRequest.Unmarshal(m, b)
}
func (m *RetrieveCategoriesByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoriesByIdRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoriesByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoriesByIdRequest.Merge(m, src)
}
func (m *RetrieveCategoriesByIdRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoriesByIdRequest.Size(m)
}
func (m *RetrieveCategoriesByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoriesByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoriesByIdRequest proto.InternalMessageInfo

func (m *RetrieveCategoriesByIdRequest) GetCategoryIds() []uint64 {
	if m != nil {
		return m.CategoryIds
	}
	return nil
}

type RetrieveCategoryRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCategoryRequest) Reset()         { *m = RetrieveCategoryRequest{} }
func (m *RetrieveCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoryRequest) ProtoMessage()    {}
func (*RetrieveCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{2}
}

func (m *RetrieveCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoryRequest.Unmarshal(m, b)
}
func (m *RetrieveCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoryRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoryRequest.Merge(m, src)
}
func (m *RetrieveCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoryRequest.Size(m)
}
func (m *RetrieveCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoryRequest proto.InternalMessageInfo

func (m *RetrieveCategoryRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type Category struct {
	Name                   string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId               uint64               `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Childs                 map[uint64]*Category `protobuf:"bytes,3,rep,name=childs,proto3" json:"childs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IdentificationTemplate string               `protobuf:"bytes,4,opt,name=identification_template,json=identificationTemplate,proto3" json:"identification_template,omitempty"`
	MaxVolWeight           float64              `protobuf:"fixed64,5,opt,name=max_vol_weight,json=maxVolWeight,proto3" json:"max_vol_weight,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{3}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Category) GetChilds() map[uint64]*Category {
	if m != nil {
		return m.Childs
	}
	return nil
}

func (m *Category) GetIdentificationTemplate() string {
	if m != nil {
		return m.IdentificationTemplate
	}
	return ""
}

func (m *Category) GetMaxVolWeight() float64 {
	if m != nil {
		return m.MaxVolWeight
	}
	return 0
}

type AttributeSchema struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ValueType            string   `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeSchema) Reset()         { *m = AttributeSchema{} }
func (m *AttributeSchema) String() string { return proto.CompactTextString(m) }
func (*AttributeSchema) ProtoMessage()    {}
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{4}
}

func (m *AttributeSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeSchema.Unmarshal(m, b)
}
func (m *AttributeSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeSchema.Marshal(b, m, deterministic)
}
func (m *AttributeSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeSchema.Merge(m, src)
}
func (m *AttributeSchema) XXX_Size() int {
	return xxx_messageInfo_AttributeSchema.Size(m)
}
func (m *AttributeSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeSchema.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeSchema proto.InternalMessageInfo

func (m *AttributeSchema) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *AttributeSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeSchema) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type RetrieveCategoriesResponse struct {
	Categories           map[uint64]*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RetrieveCategoriesResponse) Reset()         { *m = RetrieveCategoriesResponse{} }
func (m *RetrieveCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoriesResponse) ProtoMessage()    {}
func (*RetrieveCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{5}
}

func (m *RetrieveCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoriesResponse.Unmarshal(m, b)
}
func (m *RetrieveCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoriesResponse.Merge(m, src)
}
func (m *RetrieveCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoriesResponse.Size(m)
}
func (m *RetrieveCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoriesResponse proto.InternalMessageInfo

func (m *RetrieveCategoriesResponse) GetCategories() map[uint64]*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type RetrieveAttributeSchemasRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveAttributeSchemasRequest) Reset()         { *m = RetrieveAttributeSchemasRequest{} }
func (m *RetrieveAttributeSchemasRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributeSchemasRequest) ProtoMessage()    {}
func (*RetrieveAttributeSchemasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{6}
}

func (m *RetrieveAttributeSchemasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributeSchemasRequest.Unmarshal(m, b)
}
func (m *RetrieveAttributeSchemasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributeSchemasRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributeSchemasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributeSchemasRequest.Merge(m, src)
}
func (m *RetrieveAttributeSchemasRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributeSchemasRequest.Size(m)
}
func (m *RetrieveAttributeSchemasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributeSchemasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributeSchemasRequest proto.InternalMessageInfo

func (m *RetrieveAttributeSchemasRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type RetrieveAttributeDatasRequest struct {
	Entity               *pbshared.Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RetrieveAttributeDatasRequest) Reset()         { *m = RetrieveAttributeDatasRequest{} }
func (m *RetrieveAttributeDatasRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributeDatasRequest) ProtoMessage()    {}
func (*RetrieveAttributeDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{7}
}

func (m *RetrieveAttributeDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributeDatasRequest.Unmarshal(m, b)
}
func (m *RetrieveAttributeDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributeDatasRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributeDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributeDatasRequest.Merge(m, src)
}
func (m *RetrieveAttributeDatasRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributeDatasRequest.Size(m)
}
func (m *RetrieveAttributeDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributeDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributeDatasRequest proto.InternalMessageInfo

func (m *RetrieveAttributeDatasRequest) GetEntity() *pbshared.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type DeleteAttributeDatasRequest struct {
	AccessToken          string           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Entity               *pbshared.Entity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteAttributeDatasRequest) Reset()         { *m = DeleteAttributeDatasRequest{} }
func (m *DeleteAttributeDatasRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAttributeDatasRequest) ProtoMessage()    {}
func (*DeleteAttributeDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{8}
}

func (m *DeleteAttributeDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAttributeDatasRequest.Unmarshal(m, b)
}
func (m *DeleteAttributeDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAttributeDatasRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAttributeDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAttributeDatasRequest.Merge(m, src)
}
func (m *DeleteAttributeDatasRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAttributeDatasRequest.Size(m)
}
func (m *DeleteAttributeDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAttributeDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAttributeDatasRequest proto.InternalMessageInfo

func (m *DeleteAttributeDatasRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *DeleteAttributeDatasRequest) GetEntity() *pbshared.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type RetrieveAttributeSchemasResponse struct {
	Attributes           map[uint64]*AttributeSchema `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RetrieveAttributeSchemasResponse) Reset()         { *m = RetrieveAttributeSchemasResponse{} }
func (m *RetrieveAttributeSchemasResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributeSchemasResponse) ProtoMessage()    {}
func (*RetrieveAttributeSchemasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{9}
}

func (m *RetrieveAttributeSchemasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributeSchemasResponse.Unmarshal(m, b)
}
func (m *RetrieveAttributeSchemasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributeSchemasResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributeSchemasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributeSchemasResponse.Merge(m, src)
}
func (m *RetrieveAttributeSchemasResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributeSchemasResponse.Size(m)
}
func (m *RetrieveAttributeSchemasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributeSchemasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributeSchemasResponse proto.InternalMessageInfo

func (m *RetrieveAttributeSchemasResponse) GetAttributes() map[uint64]*AttributeSchema {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type RetrieveAttributeDatasResponse struct {
	Attributes           map[uint64]*AttributeData `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RetrieveAttributeDatasResponse) Reset()         { *m = RetrieveAttributeDatasResponse{} }
func (m *RetrieveAttributeDatasResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveAttributeDatasResponse) ProtoMessage()    {}
func (*RetrieveAttributeDatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{10}
}

func (m *RetrieveAttributeDatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAttributeDatasResponse.Unmarshal(m, b)
}
func (m *RetrieveAttributeDatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAttributeDatasResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveAttributeDatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAttributeDatasResponse.Merge(m, src)
}
func (m *RetrieveAttributeDatasResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveAttributeDatasResponse.Size(m)
}
func (m *RetrieveAttributeDatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAttributeDatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAttributeDatasResponse proto.InternalMessageInfo

func (m *RetrieveAttributeDatasResponse) GetAttributes() map[uint64]*AttributeData {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributeDatasResponse struct {
	AttributeDataId      uint64         `protobuf:"varint,1,opt,name=attribute_data_id,json=attributeDataId,proto3" json:"attribute_data_id,omitempty"`
	Data                 *AttributeData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetAttributeDatasResponse) Reset()         { *m = SetAttributeDatasResponse{} }
func (m *SetAttributeDatasResponse) String() string { return proto.CompactTextString(m) }
func (*SetAttributeDatasResponse) ProtoMessage()    {}
func (*SetAttributeDatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{11}
}

func (m *SetAttributeDatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributeDatasResponse.Unmarshal(m, b)
}
func (m *SetAttributeDatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributeDatasResponse.Marshal(b, m, deterministic)
}
func (m *SetAttributeDatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributeDatasResponse.Merge(m, src)
}
func (m *SetAttributeDatasResponse) XXX_Size() int {
	return xxx_messageInfo_SetAttributeDatasResponse.Size(m)
}
func (m *SetAttributeDatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributeDatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributeDatasResponse proto.InternalMessageInfo

func (m *SetAttributeDatasResponse) GetAttributeDataId() uint64 {
	if m != nil {
		return m.AttributeDataId
	}
	return 0
}

func (m *SetAttributeDatasResponse) GetData() *AttributeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CloneAttributeDatasResponse struct {
	Attributes           map[uint64]*AttributeData `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CloneAttributeDatasResponse) Reset()         { *m = CloneAttributeDatasResponse{} }
func (m *CloneAttributeDatasResponse) String() string { return proto.CompactTextString(m) }
func (*CloneAttributeDatasResponse) ProtoMessage()    {}
func (*CloneAttributeDatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{12}
}

func (m *CloneAttributeDatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributeDatasResponse.Unmarshal(m, b)
}
func (m *CloneAttributeDatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributeDatasResponse.Marshal(b, m, deterministic)
}
func (m *CloneAttributeDatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributeDatasResponse.Merge(m, src)
}
func (m *CloneAttributeDatasResponse) XXX_Size() int {
	return xxx_messageInfo_CloneAttributeDatasResponse.Size(m)
}
func (m *CloneAttributeDatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributeDatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributeDatasResponse proto.InternalMessageInfo

func (m *CloneAttributeDatasResponse) GetAttributes() map[uint64]*AttributeData {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributeDatasRequest struct {
	// Types that are valid to be assigned to Corpus:
	//	*SetAttributeDatasRequest_Authorization_
	//	*SetAttributeDatasRequest_Data
	Corpus               isSetAttributeDatasRequest_Corpus `protobuf_oneof:"corpus"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SetAttributeDatasRequest) Reset()         { *m = SetAttributeDatasRequest{} }
func (m *SetAttributeDatasRequest) String() string { return proto.CompactTextString(m) }
func (*SetAttributeDatasRequest) ProtoMessage()    {}
func (*SetAttributeDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{13}
}

func (m *SetAttributeDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributeDatasRequest.Unmarshal(m, b)
}
func (m *SetAttributeDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributeDatasRequest.Marshal(b, m, deterministic)
}
func (m *SetAttributeDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributeDatasRequest.Merge(m, src)
}
func (m *SetAttributeDatasRequest) XXX_Size() int {
	return xxx_messageInfo_SetAttributeDatasRequest.Size(m)
}
func (m *SetAttributeDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributeDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributeDatasRequest proto.InternalMessageInfo

type isSetAttributeDatasRequest_Corpus interface {
	isSetAttributeDatasRequest_Corpus()
}

type SetAttributeDatasRequest_Authorization_ struct {
	Authorization *SetAttributeDatasRequest_Authorization `protobuf:"bytes,1,opt,name=authorization,proto3,oneof"`
}

type SetAttributeDatasRequest_Data struct {
	Data *AttributeData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SetAttributeDatasRequest_Authorization_) isSetAttributeDatasRequest_Corpus() {}

func (*SetAttributeDatasRequest_Data) isSetAttributeDatasRequest_Corpus() {}

func (m *SetAttributeDatasRequest) GetCorpus() isSetAttributeDatasRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return nil
}

func (m *SetAttributeDatasRequest) GetAuthorization() *SetAttributeDatasRequest_Authorization {
	if x, ok := m.GetCorpus().(*SetAttributeDatasRequest_Authorization_); ok {
		return x.Authorization
	}
	return nil
}

func (m *SetAttributeDatasRequest) GetData() *AttributeData {
	if x, ok := m.GetCorpus().(*SetAttributeDatasRequest_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SetAttributeDatasRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SetAttributeDatasRequest_Authorization_)(nil),
		(*SetAttributeDatasRequest_Data)(nil),
	}
}

type SetAttributeDatasRequest_Authorization struct {
	AccessToken          string           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Entity               *pbshared.Entity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetAttributeDatasRequest_Authorization) Reset() {
	*m = SetAttributeDatasRequest_Authorization{}
}
func (m *SetAttributeDatasRequest_Authorization) String() string { return proto.CompactTextString(m) }
func (*SetAttributeDatasRequest_Authorization) ProtoMessage()    {}
func (*SetAttributeDatasRequest_Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{13, 0}
}

func (m *SetAttributeDatasRequest_Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributeDatasRequest_Authorization.Unmarshal(m, b)
}
func (m *SetAttributeDatasRequest_Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributeDatasRequest_Authorization.Marshal(b, m, deterministic)
}
func (m *SetAttributeDatasRequest_Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributeDatasRequest_Authorization.Merge(m, src)
}
func (m *SetAttributeDatasRequest_Authorization) XXX_Size() int {
	return xxx_messageInfo_SetAttributeDatasRequest_Authorization.Size(m)
}
func (m *SetAttributeDatasRequest_Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributeDatasRequest_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributeDatasRequest_Authorization proto.InternalMessageInfo

func (m *SetAttributeDatasRequest_Authorization) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SetAttributeDatasRequest_Authorization) GetEntity() *pbshared.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type ChangeEntityAttributeDatasRequest struct {
	AccessToken          string           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	From                 *pbshared.Entity `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Dest                 *pbshared.Entity `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChangeEntityAttributeDatasRequest) Reset()         { *m = ChangeEntityAttributeDatasRequest{} }
func (m *ChangeEntityAttributeDatasRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEntityAttributeDatasRequest) ProtoMessage()    {}
func (*ChangeEntityAttributeDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{14}
}

func (m *ChangeEntityAttributeDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEntityAttributeDatasRequest.Unmarshal(m, b)
}
func (m *ChangeEntityAttributeDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEntityAttributeDatasRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEntityAttributeDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEntityAttributeDatasRequest.Merge(m, src)
}
func (m *ChangeEntityAttributeDatasRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEntityAttributeDatasRequest.Size(m)
}
func (m *ChangeEntityAttributeDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEntityAttributeDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEntityAttributeDatasRequest proto.InternalMessageInfo

func (m *ChangeEntityAttributeDatasRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ChangeEntityAttributeDatasRequest) GetFrom() *pbshared.Entity {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChangeEntityAttributeDatasRequest) GetDest() *pbshared.Entity {
	if m != nil {
		return m.Dest
	}
	return nil
}

type CloneAttributeDatasRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	FromEntityId         uint64   `protobuf:"varint,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	DestEntityId         uint64   `protobuf:"varint,3,opt,name=dest_entity_id,json=destEntityId,proto3" json:"dest_entity_id,omitempty"`
	EntityTable          string   `protobuf:"bytes,4,opt,name=entity_table,json=entityTable,proto3" json:"entity_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneAttributeDatasRequest) Reset()         { *m = CloneAttributeDatasRequest{} }
func (m *CloneAttributeDatasRequest) String() string { return proto.CompactTextString(m) }
func (*CloneAttributeDatasRequest) ProtoMessage()    {}
func (*CloneAttributeDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{15}
}

func (m *CloneAttributeDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneAttributeDatasRequest.Unmarshal(m, b)
}
func (m *CloneAttributeDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneAttributeDatasRequest.Marshal(b, m, deterministic)
}
func (m *CloneAttributeDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneAttributeDatasRequest.Merge(m, src)
}
func (m *CloneAttributeDatasRequest) XXX_Size() int {
	return xxx_messageInfo_CloneAttributeDatasRequest.Size(m)
}
func (m *CloneAttributeDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneAttributeDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneAttributeDatasRequest proto.InternalMessageInfo

func (m *CloneAttributeDatasRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CloneAttributeDatasRequest) GetFromEntityId() uint64 {
	if m != nil {
		return m.FromEntityId
	}
	return 0
}

func (m *CloneAttributeDatasRequest) GetDestEntityId() uint64 {
	if m != nil {
		return m.DestEntityId
	}
	return 0
}

func (m *CloneAttributeDatasRequest) GetEntityTable() string {
	if m != nil {
		return m.EntityTable
	}
	return ""
}

type AttributeData struct {
	SchemaId             uint64   `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeData) Reset()         { *m = AttributeData{} }
func (m *AttributeData) String() string { return proto.CompactTextString(m) }
func (*AttributeData) ProtoMessage()    {}
func (*AttributeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{16}
}

func (m *AttributeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeData.Unmarshal(m, b)
}
func (m *AttributeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeData.Marshal(b, m, deterministic)
}
func (m *AttributeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeData.Merge(m, src)
}
func (m *AttributeData) XXX_Size() int {
	return xxx_messageInfo_AttributeData.Size(m)
}
func (m *AttributeData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeData.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeData proto.InternalMessageInfo

func (m *AttributeData) GetSchemaId() uint64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *AttributeData) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type PredictCategoryRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictCategoryRequest) Reset()         { *m = PredictCategoryRequest{} }
func (m *PredictCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryRequest) ProtoMessage()    {}
func (*PredictCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{17}
}

func (m *PredictCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryRequest.Unmarshal(m, b)
}
func (m *PredictCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryRequest.Marshal(b, m, deterministic)
}
func (m *PredictCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryRequest.Merge(m, src)
}
func (m *PredictCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryRequest.Size(m)
}
func (m *PredictCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryRequest proto.InternalMessageInfo

func (m *PredictCategoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PredictCategoryResponse struct {
	CategoryId           uint64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Score                float64   `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PredictCategoryResponse) Reset()         { *m = PredictCategoryResponse{} }
func (m *PredictCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*PredictCategoryResponse) ProtoMessage()    {}
func (*PredictCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{18}
}

func (m *PredictCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictCategoryResponse.Unmarshal(m, b)
}
func (m *PredictCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictCategoryResponse.Marshal(b, m, deterministic)
}
func (m *PredictCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictCategoryResponse.Merge(m, src)
}
func (m *PredictCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_PredictCategoryResponse.Size(m)
}
func (m *PredictCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictCategoryResponse proto.InternalMessageInfo

func (m *PredictCategoryResponse) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *PredictCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *PredictCategoryResponse) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type RetrieveCategoriesByRoleRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveCategoriesByRoleRequest) Reset()         { *m = RetrieveCategoriesByRoleRequest{} }
func (m *RetrieveCategoriesByRoleRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveCategoriesByRoleRequest) ProtoMessage()    {}
func (*RetrieveCategoriesByRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e5db2b9bc8653e, []int{19}
}

func (m *RetrieveCategoriesByRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Unmarshal(m, b)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCategoriesByRoleRequest.Merge(m, src)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveCategoriesByRoleRequest.Size(m)
}
func (m *RetrieveCategoriesByRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCategoriesByRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCategoriesByRoleRequest proto.InternalMessageInfo

func (m *RetrieveCategoriesByRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrieveShippingCategoriesRequest)(nil), "semantic.RetrieveShippingCategoriesRequest")
	proto.RegisterType((*RetrieveCategoriesByIdRequest)(nil), "semantic.RetrieveCategoriesByIdRequest")
	proto.RegisterType((*RetrieveCategoryRequest)(nil), "semantic.RetrieveCategoryRequest")
	proto.RegisterType((*Category)(nil), "semantic.Category")
	proto.RegisterMapType((map[uint64]*Category)(nil), "semantic.Category.ChildsEntry")
	proto.RegisterType((*AttributeSchema)(nil), "semantic.AttributeSchema")
	proto.RegisterType((*RetrieveCategoriesResponse)(nil), "semantic.RetrieveCategoriesResponse")
	proto.RegisterMapType((map[uint64]*Category)(nil), "semantic.RetrieveCategoriesResponse.CategoriesEntry")
	proto.RegisterType((*RetrieveAttributeSchemasRequest)(nil), "semantic.RetrieveAttributeSchemasRequest")
	proto.RegisterType((*RetrieveAttributeDatasRequest)(nil), "semantic.RetrieveAttributeDatasRequest")
	proto.RegisterType((*DeleteAttributeDatasRequest)(nil), "semantic.DeleteAttributeDatasRequest")
	proto.RegisterType((*RetrieveAttributeSchemasResponse)(nil), "semantic.RetrieveAttributeSchemasResponse")
	proto.RegisterMapType((map[uint64]*AttributeSchema)(nil), "semantic.RetrieveAttributeSchemasResponse.AttributesEntry")
	proto.RegisterType((*RetrieveAttributeDatasResponse)(nil), "semantic.RetrieveAttributeDatasResponse")
	proto.RegisterMapType((map[uint64]*AttributeData)(nil), "semantic.RetrieveAttributeDatasResponse.AttributesEntry")
	proto.RegisterType((*SetAttributeDatasResponse)(nil), "semantic.SetAttributeDatasResponse")
	proto.RegisterType((*CloneAttributeDatasResponse)(nil), "semantic.CloneAttributeDatasResponse")
	proto.RegisterMapType((map[uint64]*AttributeData)(nil), "semantic.CloneAttributeDatasResponse.AttributesEntry")
	proto.RegisterType((*SetAttributeDatasRequest)(nil), "semantic.SetAttributeDatasRequest")
	proto.RegisterType((*SetAttributeDatasRequest_Authorization)(nil), "semantic.SetAttributeDatasRequest.Authorization")
	proto.RegisterType((*ChangeEntityAttributeDatasRequest)(nil), "semantic.ChangeEntityAttributeDatasRequest")
	proto.RegisterType((*CloneAttributeDatasRequest)(nil), "semantic.CloneAttributeDatasRequest")
	proto.RegisterType((*AttributeData)(nil), "semantic.AttributeData")
	proto.RegisterType((*PredictCategoryRequest)(nil), "semantic.PredictCategoryRequest")
	proto.RegisterType((*PredictCategoryResponse)(nil), "semantic.PredictCategoryResponse")
	proto.RegisterType((*RetrieveCategoriesByRoleRequest)(nil), "semantic.RetrieveCategoriesByRoleRequest")
}

func init() {
	proto.RegisterFile("semantic.proto", fileDescriptor_32e5db2b9bc8653e)
}

var fileDescriptor_32e5db2b9bc8653e = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0xd9, 0x95, 0x47, 0xf2, 0x4f, 0x36, 0x81, 0xad, 0xd0, 0x48, 0x22, 0xb1, 0x6e,
	0xaa, 0xc6, 0x30, 0x15, 0xa8, 0x7f, 0x81, 0x2f, 0x45, 0x64, 0x1b, 0x8d, 0x50, 0x04, 0x70, 0x69,
	0x35, 0x31, 0x8c, 0x02, 0xc2, 0x8a, 0x5c, 0x4b, 0x44, 0x28, 0x92, 0x21, 0x57, 0x6a, 0xd4, 0x53,
	0xaf, 0xbd, 0xf4, 0x1d, 0xfa, 0x02, 0x79, 0x8b, 0xde, 0x7a, 0xea, 0xa9, 0xe7, 0x3e, 0x41, 0xcf,
	0x3d, 0x15, 0xdc, 0xe5, 0x8a, 0x94, 0x44, 0x4a, 0x42, 0xeb, 0xa0, 0x97, 0xde, 0xb8, 0xb3, 0x33,
	0xdf, 0xfc, 0xef, 0x0c, 0x61, 0xcb, 0x27, 0x03, 0x6c, 0x53, 0x53, 0x57, 0x5d, 0xcf, 0xa1, 0x0e,
	0x2a, 0x88, 0xb3, 0xbc, 0x37, 0xc2, 0x96, 0x69, 0x60, 0x4a, 0xea, 0xe2, 0x83, 0xb3, 0xc8, 0xfb,
	0x3d, 0xc7, 0xe9, 0x59, 0xa4, 0xce, 0x4e, 0xdd, 0xe1, 0x75, 0x9d, 0x0c, 0x5c, 0x3a, 0x0e, 0x2f,
	0x6f, 0xfb, 0x7d, 0xec, 0x11, 0xa3, 0x4e, 0x6c, 0x6a, 0x0a, 0xa2, 0xd2, 0x82, 0xaa, 0x46, 0xa8,
	0x67, 0x92, 0x11, 0xb9, 0xe8, 0x9b, 0xae, 0x6b, 0xda, 0xbd, 0x13, 0x4c, 0x49, 0xcf, 0xf1, 0x4c,
	0xe2, 0x6b, 0xe4, 0xf5, 0x90, 0xf8, 0x14, 0x1d, 0xc0, 0xd6, 0x00, 0xbf, 0xe9, 0x8c, 0x1c, 0xab,
	0xf3, 0x1d, 0x31, 0x7b, 0x7d, 0x5a, 0x96, 0x2a, 0x52, 0x4d, 0xd2, 0x4a, 0x03, 0xfc, 0xe6, 0x85,
	0x63, 0xbd, 0x64, 0x34, 0xa5, 0x09, 0xf7, 0x04, 0x54, 0x04, 0xd1, 0x1c, 0xb7, 0x0c, 0x01, 0x53,
	0x85, 0x92, 0xce, 0x2f, 0xc6, 0x1d, 0xd3, 0xf0, 0xcb, 0x52, 0x25, 0x57, 0xcb, 0x6b, 0x45, 0x41,
	0x6b, 0x19, 0xbe, 0x72, 0x0c, 0x7b, 0x33, 0x18, 0x63, 0x21, 0xfd, 0x00, 0x8a, 0x31, 0x69, 0x66,
	0x41, 0x5e, 0x83, 0x48, 0x58, 0xf9, 0x39, 0x0b, 0x05, 0x21, 0x84, 0x10, 0xe4, 0x6d, 0x3c, 0x20,
	0x8c, 0x6d, 0x43, 0x63, 0xdf, 0x68, 0x1f, 0x36, 0x5c, 0xec, 0x11, 0x9b, 0x06, 0xf2, 0x59, 0x26,
	0x5f, 0xe0, 0x84, 0x96, 0x81, 0x3e, 0x83, 0x75, 0xbd, 0x6f, 0x5a, 0x86, 0x5f, 0xce, 0x55, 0x72,
	0xb5, 0x62, 0xe3, 0xbe, 0x3a, 0x09, 0xbf, 0x00, 0x55, 0x4f, 0x18, 0xc3, 0x99, 0x4d, 0xbd, 0xb1,
	0x16, 0x72, 0xa3, 0xcf, 0x61, 0xcf, 0x34, 0x82, 0x90, 0x5e, 0x9b, 0x3a, 0xa6, 0xa6, 0x63, 0x77,
	0x28, 0x19, 0xb8, 0x16, 0xa6, 0xa4, 0x9c, 0x67, 0xba, 0x77, 0xa7, 0xaf, 0xdb, 0xe1, 0x6d, 0x42,
	0x50, 0xd7, 0xe6, 0x83, 0x2a, 0x3f, 0x87, 0x62, 0x4c, 0x2b, 0xda, 0x81, 0xdc, 0x2b, 0x32, 0x0e,
	0x9d, 0x0f, 0x3e, 0x51, 0x0d, 0xd6, 0x46, 0xd8, 0x1a, 0x12, 0xe6, 0x50, 0xb1, 0x81, 0xe6, 0xcd,
	0xd6, 0x38, 0xc3, 0x71, 0xf6, 0x89, 0xa4, 0x10, 0xd8, 0x7e, 0x4a, 0xa9, 0x67, 0x76, 0x87, 0x94,
	0x5c, 0xe8, 0x7d, 0x32, 0xc0, 0x4b, 0xe3, 0x3a, 0x09, 0x65, 0x36, 0x16, 0xca, 0x7b, 0x00, 0x0c,
	0xb4, 0x43, 0xc7, 0x2e, 0x29, 0xe7, 0xd8, 0xcd, 0x06, 0xa3, 0xb4, 0xc7, 0x2e, 0x51, 0x7e, 0x91,
	0x40, 0x9e, 0xaf, 0x05, 0x8d, 0xf8, 0xae, 0x63, 0xfb, 0x04, 0xb5, 0x41, 0xe0, 0x9b, 0x84, 0x97,
	0x41, 0xb1, 0xf1, 0x49, 0x64, 0x78, 0xba, 0xa4, 0x1a, 0x91, 0x78, 0x16, 0x62, 0x38, 0xf2, 0xd7,
	0xb0, 0x3d, 0x73, 0xfd, 0xaf, 0xc3, 0xd5, 0x84, 0x07, 0xc2, 0x98, 0x99, 0xb0, 0xf9, 0x2b, 0x97,
	0xe5, 0x97, 0x51, 0x5b, 0x4c, 0x30, 0x4e, 0x31, 0x8d, 0x10, 0x1e, 0xc2, 0x3a, 0x6f, 0x49, 0x26,
	0x5c, 0x6c, 0x6c, 0xa9, 0xbc, 0x51, 0xd5, 0x33, 0x46, 0xd5, 0xc2, 0x5b, 0xa5, 0x0f, 0xfb, 0xa7,
	0xc4, 0x22, 0x34, 0x05, 0xa6, 0x0a, 0x25, 0xac, 0xeb, 0xc4, 0xf7, 0x3b, 0xd4, 0x79, 0x45, 0xec,
	0xb0, 0xf2, 0x8b, 0x9c, 0xd6, 0x0e, 0x48, 0x31, 0x4d, 0xd9, 0x85, 0x9a, 0x7e, 0x97, 0xa0, 0x92,
	0xee, 0x77, 0x98, 0xc4, 0x2b, 0x00, 0x2c, 0xee, 0x44, 0x12, 0x8f, 0xe7, 0x93, 0x98, 0x26, 0xaf,
	0x4e, 0x2e, 0x44, 0x2a, 0x23, 0x34, 0xf9, 0x32, 0x56, 0xa6, 0xa9, 0xa9, 0xac, 0x4f, 0xa7, 0xf2,
	0x6e, 0xa4, 0x7b, 0x46, 0x67, 0x3c, 0xa3, 0xbf, 0x49, 0x70, 0x3f, 0x2d, 0x1d, 0xa1, 0x63, 0x97,
	0x09, 0x8e, 0x3d, 0x59, 0xe0, 0xd8, 0x94, 0xf4, 0x42, 0xb7, 0x5e, 0xac, 0xe2, 0xd6, 0xd1, 0xb4,
	0x5b, 0x7b, 0x09, 0x6e, 0x05, 0x1a, 0xe3, 0x4e, 0x51, 0xb8, 0x7b, 0x41, 0x68, 0x8a, 0x3b, 0x8f,
	0xe0, 0xd6, 0xc4, 0x84, 0x8e, 0x81, 0x29, 0x8e, 0xca, 0x74, 0x1b, 0xc7, 0x45, 0x5a, 0x06, 0x3a,
	0x84, 0x7c, 0xc0, 0xb1, 0x4c, 0x35, 0x63, 0x52, 0x7e, 0x95, 0x60, 0xff, 0xc4, 0x72, 0xec, 0xb4,
	0x38, 0x7e, 0x93, 0x10, 0xc7, 0x4f, 0x63, 0xfd, 0x96, 0x2e, 0xfa, 0x9f, 0x04, 0xf1, 0xc7, 0x2c,
	0x94, 0x13, 0xa2, 0xc8, 0x9b, 0xeb, 0x12, 0x36, 0xf1, 0x90, 0xf6, 0x1d, 0xcf, 0xfc, 0x9e, 0xbd,
	0xe2, 0x61, 0xab, 0x3e, 0x8e, 0x70, 0xd3, 0x44, 0xd5, 0xa7, 0x71, 0xb9, 0x67, 0x19, 0x6d, 0x1a,
	0x08, 0x1d, 0xad, 0x14, 0xf2, 0x67, 0x19, 0x1e, 0x74, 0xf9, 0x0a, 0x36, 0xa7, 0x00, 0x6f, 0xb0,
	0xed, 0x9b, 0x05, 0x58, 0xd7, 0x1d, 0xcf, 0x1d, 0xfa, 0xca, 0x4f, 0x12, 0x54, 0x4f, 0xfa, 0xd8,
	0xee, 0x11, 0xce, 0xf2, 0x8f, 0x5f, 0x1c, 0x05, 0xf2, 0xd7, 0x9e, 0x33, 0x48, 0x51, 0xcc, 0xee,
	0x02, 0x1e, 0x83, 0xf8, 0x94, 0x4d, 0x91, 0x04, 0x9e, 0xe0, 0x4e, 0x79, 0x2b, 0x81, 0x9c, 0x58,
	0x30, 0x2b, 0x5b, 0x72, 0x00, 0x5b, 0x81, 0xb6, 0x0e, 0xf7, 0x35, 0xda, 0x00, 0x4a, 0x01, 0x95,
	0xeb, 0x6a, 0x19, 0x01, 0x57, 0xa0, 0x2f, 0xc6, 0x95, 0xe3, 0x5c, 0x01, 0x75, 0xc2, 0x55, 0x85,
	0x52, 0xc8, 0x40, 0x71, 0xd7, 0x12, 0x83, 0xbe, 0xc8, 0x69, 0xed, 0x80, 0xa4, 0x9c, 0xc2, 0xe6,
	0x94, 0xa9, 0xc1, 0xf2, 0xe1, 0xb3, 0xd7, 0x28, 0x6a, 0xbf, 0x02, 0x27, 0xb4, 0x0c, 0xb4, 0x0b,
	0xeb, 0xac, 0x10, 0xfd, 0x72, 0xb6, 0x92, 0xab, 0x6d, 0x68, 0xe1, 0x49, 0x51, 0x61, 0xf7, 0xdc,
	0x23, 0x86, 0xa9, 0xd3, 0xd9, 0x6d, 0xe8, 0x0e, 0xac, 0x51, 0x93, 0x5a, 0x62, 0xc1, 0xe1, 0x07,
	0xe5, 0x07, 0x09, 0xf6, 0xe6, 0x04, 0xc2, 0x76, 0x5c, 0x3a, 0xe7, 0x55, 0x28, 0x88, 0xd3, 0x82,
	0xe9, 0x38, 0xe1, 0x09, 0x4c, 0xf0, 0x75, 0xc7, 0xe3, 0xe3, 0x5f, 0xd2, 0xf8, 0x41, 0xe9, 0x46,
	0x23, 0x33, 0xbe, 0x05, 0x6a, 0x8e, 0x45, 0x84, 0xed, 0x5f, 0x40, 0xde, 0x73, 0x84, 0xe9, 0xcd,
	0xc3, 0xbf, 0x9a, 0x35, 0xef, 0xa1, 0xb6, 0xe3, 0x13, 0x6f, 0x64, 0xea, 0xe4, 0xc8, 0xf5, 0x9c,
	0x91, 0x69, 0x10, 0x4f, 0x2b, 0xe8, 0x8e, 0xed, 0x0f, 0x07, 0xc1, 0xd7, 0x80, 0x78, 0x7a, 0x1f,
	0xdb, 0x54, 0x63, 0x82, 0x8d, 0x3f, 0xf3, 0xb0, 0x73, 0xc1, 0xd9, 0xcf, 0x43, 0x6e, 0x1f, 0xb5,
	0x01, 0xcd, 0x2b, 0x46, 0xbb, 0x2a, 0x5f, 0x89, 0x55, 0xb1, 0x12, 0xab, 0x67, 0xc1, 0x4a, 0x2c,
	0x1f, 0xac, 0xb2, 0x6e, 0x28, 0x19, 0xf4, 0x3a, 0x5a, 0x64, 0xe6, 0xf7, 0x63, 0x74, 0x38, 0x8f,
	0x92, 0xba, 0x45, 0xaf, 0xac, 0xf2, 0x2b, 0xd8, 0x99, 0xdd, 0x81, 0x51, 0x35, 0x55, 0x56, 0x54,
	0x84, 0x9c, 0x90, 0x2c, 0x25, 0x83, 0x7c, 0x28, 0xa7, 0x4d, 0x62, 0xf4, 0xd1, 0x2a, 0xd3, 0x9a,
	0x83, 0x3f, 0x5a, 0x7d, 0xb0, 0x2b, 0x19, 0x34, 0x80, 0xdd, 0xe4, 0x29, 0x89, 0x3e, 0x5c, 0x3e,
	0x47, 0xb9, 0xc2, 0xda, 0xaa, 0x03, 0x57, 0xc9, 0xa0, 0x2e, 0xdc, 0x9a, 0x7b, 0x7d, 0x91, 0xb2,
	0xfc, 0x69, 0x96, 0xdf, 0x5f, 0xc8, 0x23, 0xf0, 0x6b, 0xd2, 0x63, 0xa9, 0xf1, 0x56, 0x82, 0x8d,
	0xe7, 0x61, 0x15, 0xbe, 0xab, 0x5a, 0xbb, 0xc9, 0xc4, 0x37, 0xfe, 0x78, 0x0f, 0x0a, 0xe7, 0x9e,
	0x63, 0x0c, 0x75, 0xea, 0xa3, 0x6f, 0x61, 0x7b, 0xe6, 0x59, 0x40, 0x95, 0x48, 0x2a, 0xf9, 0x89,
	0x91, 0xab, 0x0b, 0x38, 0xe2, 0xb1, 0xb9, 0xd9, 0x82, 0x7d, 0x37, 0xa1, 0x35, 0xa3, 0x8a, 0x9c,
	0xfe, 0x37, 0x4d, 0xaa, 0xc8, 0xc4, 0xbf, 0xd7, 0x95, 0x55, 0xfd, 0xdf, 0x71, 0x37, 0xd2, 0x71,
	0x48, 0x07, 0x39, 0x7d, 0x05, 0x89, 0xbf, 0xbc, 0x4b, 0x17, 0x15, 0x39, 0xa5, 0x7a, 0x94, 0x0c,
	0x32, 0xe0, 0x76, 0xc2, 0x5a, 0x81, 0x0e, 0x96, 0xac, 0xa9, 0x1c, 0xf6, 0x83, 0x95, 0x96, 0x59,
	0x25, 0x83, 0x5e, 0xc2, 0x9d, 0xa4, 0x3f, 0x37, 0x14, 0x03, 0x58, 0xf0, 0x67, 0x97, 0x6e, 0x7e,
	0x73, 0xeb, 0xaa, 0xa4, 0xd6, 0xdd, 0xae, 0x40, 0xe9, 0xae, 0x33, 0x8e, 0x8f, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x30, 0xf0, 0x59, 0x52, 0x3b, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceProvidersClient is the client API for ServiceProviders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceProvidersClient interface {
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveShippingCategories(ctx context.Context, in *RetrieveShippingCategoriesRequest, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	RetrieveAttributeSchemas(ctx context.Context, in *RetrieveAttributeSchemasRequest, opts ...grpc.CallOption) (*RetrieveAttributeSchemasResponse, error)
	RetrieveAttributeDatas(ctx context.Context, in *RetrieveAttributeDatasRequest, opts ...grpc.CallOption) (*RetrieveAttributeDatasResponse, error)
	SetAttributeDatas(ctx context.Context, opts ...grpc.CallOption) (ServiceProviders_SetAttributeDatasClient, error)
}

type serviceProvidersClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceProvidersClient(cc grpc.ClientConnInterface) ServiceProvidersClient {
	return &serviceProvidersClient{cc}
}

func (c *serviceProvidersClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) RetrieveShippingCategories(ctx context.Context, in *RetrieveShippingCategoriesRequest, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveShippingCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) RetrieveAttributeSchemas(ctx context.Context, in *RetrieveAttributeSchemasRequest, opts ...grpc.CallOption) (*RetrieveAttributeSchemasResponse, error) {
	out := new(RetrieveAttributeSchemasResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveAttributeSchemas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) RetrieveAttributeDatas(ctx context.Context, in *RetrieveAttributeDatasRequest, opts ...grpc.CallOption) (*RetrieveAttributeDatasResponse, error) {
	out := new(RetrieveAttributeDatasResponse)
	err := c.cc.Invoke(ctx, "/semantic.ServiceProviders/RetrieveAttributeDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvidersClient) SetAttributeDatas(ctx context.Context, opts ...grpc.CallOption) (ServiceProviders_SetAttributeDatasClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServiceProviders_serviceDesc.Streams[0], "/semantic.ServiceProviders/SetAttributeDatas", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceProvidersSetAttributeDatasClient{stream}
	return x, nil
}

type ServiceProviders_SetAttributeDatasClient interface {
	Send(*SetAttributeDatasRequest) error
	Recv() (*SetAttributeDatasResponse, error)
	grpc.ClientStream
}

type serviceProvidersSetAttributeDatasClient struct {
	grpc.ClientStream
}

func (x *serviceProvidersSetAttributeDatasClient) Send(m *SetAttributeDatasRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceProvidersSetAttributeDatasClient) Recv() (*SetAttributeDatasResponse, error) {
	m := new(SetAttributeDatasResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceProvidersServer is the server API for ServiceProviders service.
type ServiceProvidersServer interface {
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveShippingCategories(context.Context, *RetrieveShippingCategoriesRequest) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
	RetrieveAttributeSchemas(context.Context, *RetrieveAttributeSchemasRequest) (*RetrieveAttributeSchemasResponse, error)
	RetrieveAttributeDatas(context.Context, *RetrieveAttributeDatasRequest) (*RetrieveAttributeDatasResponse, error)
	SetAttributeDatas(ServiceProviders_SetAttributeDatasServer) error
}

// UnimplementedServiceProvidersServer can be embedded to have forward compatible implementations.
type UnimplementedServiceProvidersServer struct {
}

func (*UnimplementedServiceProvidersServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedServiceProvidersServer) RetrieveShippingCategories(ctx context.Context, req *RetrieveShippingCategoriesRequest) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveShippingCategories not implemented")
}
func (*UnimplementedServiceProvidersServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}
func (*UnimplementedServiceProvidersServer) RetrieveAttributeSchemas(ctx context.Context, req *RetrieveAttributeSchemasRequest) (*RetrieveAttributeSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributeSchemas not implemented")
}
func (*UnimplementedServiceProvidersServer) RetrieveAttributeDatas(ctx context.Context, req *RetrieveAttributeDatasRequest) (*RetrieveAttributeDatasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributeDatas not implemented")
}
func (*UnimplementedServiceProvidersServer) SetAttributeDatas(srv ServiceProviders_SetAttributeDatasServer) error {
	return status.Errorf(codes.Unimplemented, "method SetAttributeDatas not implemented")
}

func RegisterServiceProvidersServer(s *grpc.Server, srv ServiceProvidersServer) {
	s.RegisterService(&_ServiceProviders_serviceDesc, srv)
}

func _ServiceProviders_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_RetrieveShippingCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveShippingCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveShippingCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveShippingCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveShippingCategories(ctx, req.(*RetrieveShippingCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_RetrieveAttributeSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributeSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveAttributeSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveAttributeSchemas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveAttributeSchemas(ctx, req.(*RetrieveAttributeSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_RetrieveAttributeDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributeDatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvidersServer).RetrieveAttributeDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.ServiceProviders/RetrieveAttributeDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvidersServer).RetrieveAttributeDatas(ctx, req.(*RetrieveAttributeDatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProviders_SetAttributeDatas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceProvidersServer).SetAttributeDatas(&serviceProvidersSetAttributeDatasServer{stream})
}

type ServiceProviders_SetAttributeDatasServer interface {
	Send(*SetAttributeDatasResponse) error
	Recv() (*SetAttributeDatasRequest, error)
	grpc.ServerStream
}

type serviceProvidersSetAttributeDatasServer struct {
	grpc.ServerStream
}

func (x *serviceProvidersSetAttributeDatasServer) Send(m *SetAttributeDatasResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceProvidersSetAttributeDatasServer) Recv() (*SetAttributeDatasRequest, error) {
	m := new(SetAttributeDatasRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ServiceProviders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.ServiceProviders",
	HandlerType: (*ServiceProvidersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategories",
			Handler:    _ServiceProviders_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveShippingCategories",
			Handler:    _ServiceProviders_RetrieveShippingCategories_Handler,
		},
		{
			MethodName: "RetrieveCategory",
			Handler:    _ServiceProviders_RetrieveCategory_Handler,
		},
		{
			MethodName: "RetrieveAttributeSchemas",
			Handler:    _ServiceProviders_RetrieveAttributeSchemas_Handler,
		},
		{
			MethodName: "RetrieveAttributeDatas",
			Handler:    _ServiceProviders_RetrieveAttributeDatas_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetAttributeDatas",
			Handler:       _ServiceProviders_SetAttributeDatas_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "semantic.proto",
}

// MerchantsClient is the client API for Merchants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsClient interface {
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
}

type merchantsClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantsClient(cc grpc.ClientConnInterface) MerchantsClient {
	return &merchantsClient{cc}
}

func (c *merchantsClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Merchants/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.Merchants/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServer is the server API for Merchants service.
type MerchantsServer interface {
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
}

// UnimplementedMerchantsServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServer struct {
}

func (*UnimplementedMerchantsServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedMerchantsServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}

func RegisterMerchantsServer(s *grpc.Server, srv MerchantsServer) {
	s.RegisterService(&_Merchants_serviceDesc, srv)
}

func _Merchants_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Merchants/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchants_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Merchants/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merchants_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Merchants",
	HandlerType: (*MerchantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategories",
			Handler:    _Merchants_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveCategory",
			Handler:    _Merchants_RetrieveCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error)
	RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveCategoriesById(ctx context.Context, in *RetrieveCategoriesByIdRequest, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error)
	RetrieveAttributeSchemas(ctx context.Context, in *RetrieveAttributeSchemasRequest, opts ...grpc.CallOption) (*RetrieveAttributeSchemasResponse, error)
	RetrieveAttributeDatas(ctx context.Context, in *RetrieveAttributeDatasRequest, opts ...grpc.CallOption) (*RetrieveAttributeDatasResponse, error)
	SetAttributeDatas(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributeDatasClient, error)
	ChangeEntityAttributeDatas(ctx context.Context, in *ChangeEntityAttributeDatasRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CloneAttributeDatas(ctx context.Context, in *CloneAttributeDatasRequest, opts ...grpc.CallOption) (*CloneAttributeDatasResponse, error)
	DeleteAttributeDatas(ctx context.Context, in *DeleteAttributeDatasRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) PredictCategory(ctx context.Context, opts ...grpc.CallOption) (Products_PredictCategoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[0], "/semantic.Products/PredictCategory", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsPredictCategoryClient{stream}
	return x, nil
}

type Products_PredictCategoryClient interface {
	Send(*PredictCategoryRequest) error
	Recv() (*PredictCategoryResponse, error)
	grpc.ClientStream
}

type productsPredictCategoryClient struct {
	grpc.ClientStream
}

func (x *productsPredictCategoryClient) Send(m *PredictCategoryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsPredictCategoryClient) Recv() (*PredictCategoryResponse, error) {
	m := new(PredictCategoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) RetrieveCategory(ctx context.Context, in *RetrieveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveCategoriesById(ctx context.Context, in *RetrieveCategoriesByIdRequest, opts ...grpc.CallOption) (*RetrieveCategoriesResponse, error) {
	out := new(RetrieveCategoriesResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveCategoriesById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveAttributeSchemas(ctx context.Context, in *RetrieveAttributeSchemasRequest, opts ...grpc.CallOption) (*RetrieveAttributeSchemasResponse, error) {
	out := new(RetrieveAttributeSchemasResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveAttributeSchemas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) RetrieveAttributeDatas(ctx context.Context, in *RetrieveAttributeDatasRequest, opts ...grpc.CallOption) (*RetrieveAttributeDatasResponse, error) {
	out := new(RetrieveAttributeDatasResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/RetrieveAttributeDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) SetAttributeDatas(ctx context.Context, opts ...grpc.CallOption) (Products_SetAttributeDatasClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[1], "/semantic.Products/SetAttributeDatas", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsSetAttributeDatasClient{stream}
	return x, nil
}

type Products_SetAttributeDatasClient interface {
	Send(*SetAttributeDatasRequest) error
	Recv() (*SetAttributeDatasResponse, error)
	grpc.ClientStream
}

type productsSetAttributeDatasClient struct {
	grpc.ClientStream
}

func (x *productsSetAttributeDatasClient) Send(m *SetAttributeDatasRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productsSetAttributeDatasClient) Recv() (*SetAttributeDatasResponse, error) {
	m := new(SetAttributeDatasResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) ChangeEntityAttributeDatas(ctx context.Context, in *ChangeEntityAttributeDatasRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/semantic.Products/ChangeEntityAttributeDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CloneAttributeDatas(ctx context.Context, in *CloneAttributeDatasRequest, opts ...grpc.CallOption) (*CloneAttributeDatasResponse, error) {
	out := new(CloneAttributeDatasResponse)
	err := c.cc.Invoke(ctx, "/semantic.Products/CloneAttributeDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteAttributeDatas(ctx context.Context, in *DeleteAttributeDatasRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/semantic.Products/DeleteAttributeDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	PredictCategory(Products_PredictCategoryServer) error
	RetrieveCategory(context.Context, *RetrieveCategoryRequest) (*Category, error)
	RetrieveCategories(context.Context, *empty.Empty) (*RetrieveCategoriesResponse, error)
	RetrieveCategoriesById(context.Context, *RetrieveCategoriesByIdRequest) (*RetrieveCategoriesResponse, error)
	RetrieveAttributeSchemas(context.Context, *RetrieveAttributeSchemasRequest) (*RetrieveAttributeSchemasResponse, error)
	RetrieveAttributeDatas(context.Context, *RetrieveAttributeDatasRequest) (*RetrieveAttributeDatasResponse, error)
	SetAttributeDatas(Products_SetAttributeDatasServer) error
	ChangeEntityAttributeDatas(context.Context, *ChangeEntityAttributeDatasRequest) (*empty.Empty, error)
	CloneAttributeDatas(context.Context, *CloneAttributeDatasRequest) (*CloneAttributeDatasResponse, error)
	DeleteAttributeDatas(context.Context, *DeleteAttributeDatasRequest) (*empty.Empty, error)
}

// UnimplementedProductsServer can be embedded to have forward compatible implementations.
type UnimplementedProductsServer struct {
}

func (*UnimplementedProductsServer) PredictCategory(srv Products_PredictCategoryServer) error {
	return status.Errorf(codes.Unimplemented, "method PredictCategory not implemented")
}
func (*UnimplementedProductsServer) RetrieveCategory(ctx context.Context, req *RetrieveCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategory not implemented")
}
func (*UnimplementedProductsServer) RetrieveCategories(ctx context.Context, req *empty.Empty) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategories not implemented")
}
func (*UnimplementedProductsServer) RetrieveCategoriesById(ctx context.Context, req *RetrieveCategoriesByIdRequest) (*RetrieveCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCategoriesById not implemented")
}
func (*UnimplementedProductsServer) RetrieveAttributeSchemas(ctx context.Context, req *RetrieveAttributeSchemasRequest) (*RetrieveAttributeSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributeSchemas not implemented")
}
func (*UnimplementedProductsServer) RetrieveAttributeDatas(ctx context.Context, req *RetrieveAttributeDatasRequest) (*RetrieveAttributeDatasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAttributeDatas not implemented")
}
func (*UnimplementedProductsServer) SetAttributeDatas(srv Products_SetAttributeDatasServer) error {
	return status.Errorf(codes.Unimplemented, "method SetAttributeDatas not implemented")
}
func (*UnimplementedProductsServer) ChangeEntityAttributeDatas(ctx context.Context, req *ChangeEntityAttributeDatasRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEntityAttributeDatas not implemented")
}
func (*UnimplementedProductsServer) CloneAttributeDatas(ctx context.Context, req *CloneAttributeDatasRequest) (*CloneAttributeDatasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneAttributeDatas not implemented")
}
func (*UnimplementedProductsServer) DeleteAttributeDatas(ctx context.Context, req *DeleteAttributeDatasRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttributeDatas not implemented")
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_PredictCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).PredictCategory(&productsPredictCategoryServer{stream})
}

type Products_PredictCategoryServer interface {
	Send(*PredictCategoryResponse) error
	Recv() (*PredictCategoryRequest, error)
	grpc.ServerStream
}

type productsPredictCategoryServer struct {
	grpc.ServerStream
}

func (x *productsPredictCategoryServer) Send(m *PredictCategoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsPredictCategoryServer) Recv() (*PredictCategoryRequest, error) {
	m := new(PredictCategoryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_RetrieveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveCategory(ctx, req.(*RetrieveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveCategoriesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCategoriesByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveCategoriesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveCategoriesById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveCategoriesById(ctx, req.(*RetrieveCategoriesByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveAttributeSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributeSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveAttributeSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveAttributeSchemas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveAttributeSchemas(ctx, req.(*RetrieveAttributeSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_RetrieveAttributeDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAttributeDatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).RetrieveAttributeDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/RetrieveAttributeDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).RetrieveAttributeDatas(ctx, req.(*RetrieveAttributeDatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_SetAttributeDatas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).SetAttributeDatas(&productsSetAttributeDatasServer{stream})
}

type Products_SetAttributeDatasServer interface {
	Send(*SetAttributeDatasResponse) error
	Recv() (*SetAttributeDatasRequest, error)
	grpc.ServerStream
}

type productsSetAttributeDatasServer struct {
	grpc.ServerStream
}

func (x *productsSetAttributeDatasServer) Send(m *SetAttributeDatasResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productsSetAttributeDatasServer) Recv() (*SetAttributeDatasRequest, error) {
	m := new(SetAttributeDatasRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Products_ChangeEntityAttributeDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEntityAttributeDatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ChangeEntityAttributeDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/ChangeEntityAttributeDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ChangeEntityAttributeDatas(ctx, req.(*ChangeEntityAttributeDatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CloneAttributeDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneAttributeDatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CloneAttributeDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/CloneAttributeDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CloneAttributeDatas(ctx, req.(*CloneAttributeDatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteAttributeDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttributeDatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteAttributeDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/semantic.Products/DeleteAttributeDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteAttributeDatas(ctx, req.(*DeleteAttributeDatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "semantic.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveCategory",
			Handler:    _Products_RetrieveCategory_Handler,
		},
		{
			MethodName: "RetrieveCategories",
			Handler:    _Products_RetrieveCategories_Handler,
		},
		{
			MethodName: "RetrieveCategoriesById",
			Handler:    _Products_RetrieveCategoriesById_Handler,
		},
		{
			MethodName: "RetrieveAttributeSchemas",
			Handler:    _Products_RetrieveAttributeSchemas_Handler,
		},
		{
			MethodName: "RetrieveAttributeDatas",
			Handler:    _Products_RetrieveAttributeDatas_Handler,
		},
		{
			MethodName: "ChangeEntityAttributeDatas",
			Handler:    _Products_ChangeEntityAttributeDatas_Handler,
		},
		{
			MethodName: "CloneAttributeDatas",
			Handler:    _Products_CloneAttributeDatas_Handler,
		},
		{
			MethodName: "DeleteAttributeDatas",
			Handler:    _Products_DeleteAttributeDatas_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredictCategory",
			Handler:       _Products_PredictCategory_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SetAttributeDatas",
			Handler:       _Products_SetAttributeDatas_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "semantic.proto",
}
