// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: checkout/purchases.proto

package purchases

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _purchases_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Purchase with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Purchase) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PurchaseValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Items

	// no validation rules for Amount

	// no validation rules for SrcAddressId

	// no validation rules for DestAddressId

	// no validation rules for MerchantId

	// no validation rules for DistanceInKilometers

	// no validation rules for ShippingId

	return nil
}

// PurchaseValidationError is the validation error returned by
// Purchase.Validate if the designated constraints aren't met.
type PurchaseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseValidationError) ErrorName() string { return "PurchaseValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchase.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseValidationError{}

// Validate checks the field values on AgreeFinishRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AgreeFinishRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AccessToken

	// no validation rules for AgreeementToken

	// no validation rules for OrderId

	return nil
}

// AgreeFinishRequestValidationError is the validation error returned by
// AgreeFinishRequest.Validate if the designated constraints aren't met.
type AgreeFinishRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgreeFinishRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgreeFinishRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgreeFinishRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgreeFinishRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgreeFinishRequestValidationError) ErrorName() string {
	return "AgreeFinishRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AgreeFinishRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgreeFinishRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgreeFinishRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgreeFinishRequestValidationError{}

// Validate checks the field values on ConfirmRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ConfirmRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AccessToken

	// no validation rules for PurchaseId

	return nil
}

// ConfirmRequestValidationError is the validation error returned by
// ConfirmRequest.Validate if the designated constraints aren't met.
type ConfirmRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmRequestValidationError) ErrorName() string { return "ConfirmRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConfirmRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmRequestValidationError{}

// Validate checks the field values on RetrieveResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RetrieveResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PurchaseId

	if v, ok := interface{}(m.GetPurchase()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RetrieveResponseValidationError{
				field:  "Purchase",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// RetrieveResponseValidationError is the validation error returned by
// RetrieveResponse.Validate if the designated constraints aren't met.
type RetrieveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetrieveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetrieveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetrieveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetrieveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetrieveResponseValidationError) ErrorName() string { return "RetrieveResponseValidationError" }

// Error satisfies the builtin error interface
func (e RetrieveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetrieveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetrieveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetrieveResponseValidationError{}

// Validate checks the field values on AssignDestAddressRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AssignDestAddressRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AccessToken

	// no validation rules for DestAddressId

	return nil
}

// AssignDestAddressRequestValidationError is the validation error returned by
// AssignDestAddressRequest.Validate if the designated constraints aren't met.
type AssignDestAddressRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssignDestAddressRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssignDestAddressRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssignDestAddressRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssignDestAddressRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssignDestAddressRequestValidationError) ErrorName() string {
	return "AssignDestAddressRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AssignDestAddressRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssignDestAddressRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssignDestAddressRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssignDestAddressRequestValidationError{}

// Validate checks the field values on CreateRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CreateRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AccessToken

	// no validation rules for Items

	return nil
}

// CreateRequestValidationError is the validation error returned by
// CreateRequest.Validate if the designated constraints aren't met.
type CreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRequestValidationError) ErrorName() string { return "CreateRequestValidationError" }

// Error satisfies the builtin error interface
func (e CreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRequestValidationError{}

// Validate checks the field values on RetrieveCurrentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RetrieveCurrentRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AccessToken

	return nil
}

// RetrieveCurrentRequestValidationError is the validation error returned by
// RetrieveCurrentRequest.Validate if the designated constraints aren't met.
type RetrieveCurrentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetrieveCurrentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetrieveCurrentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetrieveCurrentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetrieveCurrentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetrieveCurrentRequestValidationError) ErrorName() string {
	return "RetrieveCurrentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RetrieveCurrentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetrieveCurrentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetrieveCurrentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetrieveCurrentRequestValidationError{}
